### ISSUE TITLE
chap14.1，301页，MDP的轨迹的公式是否欠妥？

### ISSUE THREAD

**Issue by WildeLau** [nndl/nndl.github.io#105]
邱老师好！

301页倒数第四行，MDP的轨迹记为：
τ = s0, a0, s1, r1, a1, · · · , sT−1, aT−1, sT , rT
这里是否应该不包括r1和rT，或者，应该包含rT-1?

**Comment by WildeLau** [comment]
另外，chap14，315页，公式14.53中的τ_{1:t−1}是否应为τ_{0:t−1}？

**Comment by SharpShip** [comment]
我觉得，r1和rT-1和rT应该都是包括在内的，因为是每个状态有一个reward;
另外我也觉得，τ_{1:t−1}应该为τ_{0:t−1};

**Comment by xpqiu** [comment]
谢谢，已修正。
