### ISSUE TITLE
pdf 排版有些怪怪的

### ISSUE THREAD

**Issue by yuchenlin** [nndl/nndl.github.io#11]
个人感觉，排版的空间利用效率不高，阅读体验不太好，打印出来也很浪费纸张

**Comment by yuchenlin** [comment]
不如托管给 gitbook

**Comment by sadscv** [comment]
我也是这样觉得的，如此精致的内容却配上这样的排版，真是可惜了。希望邱老师能够想办法提高一下我们的阅读体验。

**Comment by Light1980** [comment]
邱老师想保护版权的关系吧，这应该是出版社的要求。
