### ISSUE TITLE
chap12, 公式12.59,12.60中平方项应为正号

### ISSUE THREAD

**Issue by thinkinds** [nndl/nndl.github.io#110]
公式12.59和12.60中高斯型节点能量的项，应为正号吧，Hinton原著是这样的。

**Comment by xpqiu** [comment]
已修正，谢谢。

**Comment by xpqiu** [comment]
再次谢谢，如果方便可以留下您的名字，我会在书中致谢。

**Comment by thinkinds** [comment]
邱教授，恭喜你的大作《神经网络与深度学习》终于完成，作为一名人工智能工程师，我很高兴能做出这么一点点贡献，我的名字叫任强，如果能在您的书中被提到，将是我的荣幸。

Xipeng Qiu <notifications@github.com> 于2019年4月6日周六 下午10:01写道：
