### ISSUE TITLE
一些拼写错误及其他勘误

### ISSUE THREAD

**Issue by hyp1231** [nndl/nndl.github.io#112]
## 1. 绪论
- [x] P15 第一行 “并**进行**可能保持”->“并**尽**可能保持”
## 4. 前馈神经网络
- [ ] P98 第一行 “根据a=f(…)”这里的 f 应为 fl
- [ ] 公式 4.39 和 4.40 相同
- [ ] 4.5.3 自动微分 P103 静态计算图与动态计算图 “但灵活性比较差**低**”->“但灵活性比较差”
## 5. 卷积神经网络
- [x] 5.4.4 残差网络 第一个旁注 “并不局限**与**卷积神经网络”->“并不局限**于**卷积神经网络”
## 6. 循环神经网络
- [ ] 第一页 循环神经网络这段最后一句 “最有效的改进方式引入门控机制”->“最有效的改进方式**为**引入门控机制”（加一个“为”字）
## 7. 网络优化与正则化
- [ ] 6.5.3.2 小标题 “局部**相应**归一化”->“局部**响应**归一化”
- [ ] 6.6.1 小标题旁注 “因此**关**无法使用梯度下降”->“因此无法使用梯度下降”（多了一个‘关’字）
## 8. 注意力机制与外部记忆
- [ ] 8.8.2 自注意力模型 P195 倒数第二段 “但是无法处理变**成**的输入序列”->“但是无法处理变**长**的输入序列”
## 9. 无监督学习
- [ ] 公式 9.2 循环变量不应该为 i，而是 n
- [ ] 公式 9.29 等号右侧的应该是条件概率，“log p(x)”->“log p(x|θ)”
## 10. 模型独立的学习方式
- [ ] 本章第一段 “通过这种学习方式学习到的模型往往任务定向的”->“通过这种学习方式学习到的模型往往是任务定向的”（少了个‘是’字）
- [ ] P221 终生学习 第二段最后一句 “近年来，一些更复杂的网络（比如循环神经网络）来替代反向传播算法” 不是一个完整的句子。
- [ ] P221 倒数第一段 “深度强化学习强化学习”->“深度强化学习”
## 11. 概率图模型
- [ ] 11.3 P205 2. 变分法 第二行英文前 “变**方**法”->“变分法”
- [ ] 11.3.4 P209 最后一行 “取 个样本”公式缺失
## 13. 深度生成模型
- [ ] 概率生成模型 13.1.1 第一段第二行 p_data 下标 LaTeX 公式编辑错误
## 16. 数学基础
- [ ] A.2.2 秩：“两个**句子**的乘积”->“两个**矩阵**的乘积”
- [ ] A.2.3 单位矩阵 小标题“对角矩阵”->“单位矩阵”
- [ ] A.2.5 奇异值分解 “其中U和V分别为m\*m和n\*的正交矩阵”->“其中U和V分别为m\*m和n\*n的正交矩阵”（漏写了一个n）
- [ ] C.2.0.2 梯度下降法：公式 C.8 最后一个 x 应为向量格式的 x 而非标量格式。
- [ ] D.3.2 旁注部分，加粗部分过多

**Comment by xpqiu** [comment]
已修正，谢谢。如果方面的话，可以留下名字，我会在书中致谢。

**Comment by hyp1231** [comment]
人民大学 侯宇蓬
很喜欢邱老师的这本书，期待出版！: )
