### ISSUE TITLE
章节序号错误

### ISSUE THREAD

**Issue by reinventthewheellp** [nndl/nndl.github.io#114]
# 章节序号排版错误+pdf版本第七章
- [**pdf**版本的“**网络优化与正则化**”一节的章节序号应该是“**第七章**”，版本中错排版成“**第六章**”]

另外，“序列生成模型”的pdf老师应该还没有更新上去，页面显示404。

**Comment by reinventthewheellp** [comment]
# 章节序号排版错误+pdf版本“深度强化学习”
- **PDF**版本的**“深度强化学习”**应该是**第十五章**，错排成**第十四章**

**Comment by cqamber** [comment]
+1

**Comment by xpqiu** [comment]
已修正，谢谢。
