### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by reinventthewheellp** [nndl/nndl.github.io#115]
# 图片问题+第一章 序论 第8页 图1.2 “典型神经元结构”

- 第8页 图1.2 “典型神经元结构” 的说明被排版了到第9页下方，有欠妥当；
- 另外第8页的这张图不给出神经元中每个位置的名称却画上了指示线，作为教材欠妥当。建议采用有名称标注版本（可参考 [英文版](http://paradigmchange.me/wp/karunasena/)，[中文版](https://iot.ofweek.com/2017-06/ART-132209-8420-30148257.html)，或者直接删除指示线。

**Comment by reinventthewheellp** [comment]
不过鉴于在文章中已经说明了“细胞体”、“细胞突起”等概念，还是建议采用有标注版本的图片

**Comment by xpqiu** [comment]
已修正，谢谢。
