### ISSUE TITLE
第一章勘误、建议及其他

### ISSUE THREAD

**Issue by reinventthewheellp** [nndl/nndl.github.io#117]
# 关于第一章的一些建议、勘误及其他
- 1.3节 机器学习 第一段话 不是一个完整的句子，没有表语；
- 1.3节 机器学习 第二段话 没有解释该段首句“传统的机器学习主要关注于学习预测函数”，建议采取“假设集”和“学习算法”分开讲的方式，来突出“学习”过程（可以参考林轩田老师的”机器学习基石“相应部分）；
- 对1.3节 机器学习 图1.3 “传统机器学习的数据处理流程”中“预测”一步的不同观点：学生觉得“学习预测函数”+“利用训练好的函数预测”可能更加准确。但是这里对流程图中“结果”的看法学生尚不明确，如果“结果”得到的是一个机器学习算法模型的话，“预测”阶段更改为“学习”阶段更好；如果“结果”表示原始数据的预测结果，那个这个流程图还是有些问题，没有损失函数优化阶段；
- 1.3节 机器学习 P12 最后一行中引号内重点突出“特征”更准确呢？还是突出“好的特征”更准确？
- 1.5 节 P15 第一行，”并进行可能保持不同对象之间的拓扑关系“不像是中文句子；
- P20 第四行 CS224d 也应该更新成 CS224N了，主页https://nndl.github.io/中的推荐课程中也建议更新一下；
- 绪论这一部分的**PPT**中讲”图灵测试“的那一张PPT提供的书名（《机器能思维么？》）不合适，另外，”机器能思维么“这句话不太符合中文习惯，建议改成”机器有思维么“或者”机器能思考么“（学生没有查阅原始文献，也不敢乱说，仅作参考）；
- 绪论这一部分的**PPT**中第二页有一张神经网络和深度学习的韦恩图，学生觉得这张韦恩图可以更真实一些，交集所占各部分的面积可以更加精准（只是建议，学生没有查阅相关资料，也对其具体关系没有什么把握；

**Comment by reinventthewheellp** [comment]
学生也是刚开始学ML和DL，对一些概念和表述可能把握得不到位，如有指正错误的地方，还望老师不要怪罪，还请老师指教

**Comment by xpqiu** [comment]
1.3节 机器学习 第二段话 没有解释该段首句“传统的机器学习主要关注于学习预测函数”，建议采取“假设集”和“学习算法”分开讲的方式，来突出“学习”过程（可以参考林轩田老师的”机器学习基石“相应部分）；
对1.3节 机器学习 图1.3 “传统机器学习的数据处理流程”中“预测”一步的不同观点：学生觉得“学习预测函数”+“利用训练好的函数预测”可能更加准确。但是这里对流程图中“结果”的看法学生尚不明确，如果“结果”得到的是一个机器学习算法模型的话，“预测”阶段更改为“学习”阶段更好；如果“结果”表示原始数据的预测结果，那个这个流程图还是有些问题，没有损失函数优化阶段；

这里并没有涉及学习过程。

**Comment by xpqiu** [comment]
其它应该已修正，谢谢。
