### ISSUE TITLE
第四章p97 语句不通顺

### ISSUE THREAD

**Issue by Arlenelalala** [nndl/nndl.github.io#119]
问题：第四章 4.4节反向传播算法 P97
“误差项 δ(l) 来表示第 l 层的神经元对最终误差的影响，也反映了最终的输出对第 l 层的神经元对最终误差的敏感程度。”

可以更正为：
误差项 δ(l) 表示了第 l 层神经元对最终误差的影响，也反映了最终输出对第 l 层神经元的敏感程度。

**Comment by xpqiu** [comment]
已修正，多谢。
