### ISSUE TITLE
第七章的LSMT示例图（图7.4）中漏了对tanh(ct)的描述；

### ISSUE THREAD

**Issue by zilongwhu** [nndl/nndl.github.io#12]
书写的很好，深入浅出，支持。

**Comment by ShangruZhong** [comment]
对，图7.4右上角，c_t后接的是tanh单元，才和o_t乘积的。以及带波浪线的c在图中看起来像e。

**Comment by Guohai93** [comment]
同意，图7.4右上角，确实缺失tanh(ct)的绘制

**Comment by xpqiu** [comment]
感谢指出错误！如果方便的话可否告诉我你的名字，我在书中正式致谢：）
