### ISSUE TITLE
公式疑问 第十四章 P18 公式14.75至14.79

### ISSUE THREAD

**Issue by Zhengxuru** [nndl/nndl.github.io#121]
请问，在求配分函数的时候，为何需要先将其视为均匀分布，再引入提议分布。直接引人提议分布不就可以直接得到14.79了吗？

**Comment by xpqiu** [comment]
嗯，这里确实可以简化。已修正。之前是为了和重要性采样的形式一致。

**Comment by xpqiu** [comment]
谢谢。
