### ISSUE TITLE
第二章中一些小的错误

### ISSUE THREAD

**Issue by nongdaxiaofeng** [nndl/nndl.github.io#122]
40页正文中图2-8应改为图2-6，另为图序号是2.6，2和6之间用“.”还是“-"，应该一致。
45页2.6.1.1：”每次增加对最有信息量的特征“，就把”对“去掉。
46页：”这种方法是将机器学习模型的包裹到特征选择过程的内部。“应把包裹前的”的“去掉。

**Comment by xpqiu** [comment]
已修正，谢谢。
