### ISSUE TITLE
chp2 P44 勘误

### ISSUE THREAD

**Issue by coffeehat** [nndl/nndl.github.io#124]
# chp2 P44 勘误
- chp2（2018.9.28版） P44 多打一个句号，以下是原文：
> 文本特征 在文本情感分类任务中，样本 x为自然语言文本，类别 y ∈ {+1, −1}
分别表示正面或负面的评价。为了将样本 x从文本形式转为为向量形式，一种
简单的方式是使用词袋模型（Bag-of-Words， BoW）模型。。假设训练集合中

**Comment by coffeehat** [comment]
- [ch3 (2018.10.12版) P66：]
如果P64公式3.5引用有误，那么P66也有问题：
> 感知器是一种简单的两类线性分类模型，其分类准则与公式 (3.5)相同。

**Comment by xpqiu** [comment]
已修正，谢谢。
