### ISSUE TITLE
chp3 P70 引用错误

### ISSUE THREAD

**Issue by coffeehat** [nndl/nndl.github.io#125]
# chp3 (2018.10.12版) P70 引用错误
- chp3 (2018.10.12版) P70 原文如下：
> 这个方法非常简单，只需要在算法3.3中增加一个 w¯ ，并且在处理每一个样
本后，更新

算法3.3是广义感知器学习算法，这里应该引到算法3.1

**Comment by coffeehat** [comment]
# chp4 (2018.10.14版) P91 语句不通
- chp4 (2018.10.14版) P91 原文如下：
> 为了增强记忆网络的记忆容量，可以引入外部记忆单元和读写机制，用来一
些网络的中间状态，称为记忆增强网络（Memory-Augmented Neural Network）

其中“用来一些网络的中间状态”不通

**Comment by xpqiu** [comment]
已修正，谢谢。
