### ISSUE TITLE
chap7 P158 画图错误

### ISSUE THREAD

**Issue by yangjinray** [nndl/nndl.github.io#126]
#问题描述+页号或公式号

-[chap7]
-[p158]

图7.3中(b)图，“按整个数据集迭代的损失变化”，三条loss下降曲线的位置可能有错误，麻烦老师查证一下。

**Comment by xpqiu** [comment]
谢谢，三种批量大小对应的学习率并不一致，因此并不是严格对比。
已加上说明。
