### ISSUE TITLE
第10章若干修改

### ISSUE THREAD

**Issue by lihaocruiser** [nndl/nndl.github.io#13]
- [ ] 143页，10.1节最后一句：漏掉了连字符
原文：n元语言模型的困惑度范围一般为`501000`之间
修改：`50-1000`

- [ ] 144页，第2行：漏掉了"属于"符号
原文：第 k 列向量 `m_{k} R^{d1}`表示词汇表中第 k 个词对应的稠密向量
修改：`m_{k} \in R^{d1}` 

- [ ] 159页，第3行：漏了"的"
原文：这两个模型是著名的词嵌入学习工具 word2vec 中包含两种模型
修改：这两个模型是著名的词嵌入学习工具 word2vec 中包含`的`两种模型

- [ ] 161页，倒数第2行，10.3节的负采样部分：对负样本数量的描述，小规模应改为大规模
原文：通常小规模数据 k 的取值范围在5\~20，而`小`规模数据 k 可以非常小2\~5
修改：通常小规模数据 k 的取值范围在5\~20，而`大`规模数据 k 可以小至2\~5
Mikolov原文：Our experiments indicate that values of k in the range 5–20 are useful for small training datasets, while for **large** datasets the k can be as small as 2–5. [arXiv 1310.4546]

**Comment by xpqiu** [comment]
多谢，已修正。

**Comment by xpqiu** [comment]
感谢指出错误！如果方便的话可否告诉我你的名字，我在书中正式致谢：）

**Comment by lihaocruiser** [comment]
李浩
