### ISSUE TITLE
第六章 循环神经网络

### ISSUE THREAD

**Issue by xiaokongkong** [nndl/nndl.github.io#132]
#问题描述+页号或公式号

-[1] 134页，公式（6.14）里面的s_t-1 ,是否应该为s‘_t-1呢? 不然和公式（6.16）对不上号；在（6.19）下面多了一个小方框；
-[2] 135页，6.3节 应用到机器学习  ，下面的第一段，“同步序列到序列模式” 可以改为 “同步 的 序列到序列模式”，以保持和6.3.2小节的标题一致;
-[3] 141页，6.5.1节 改进方案， 下面的第一段，最后一句，“比较有效的方式通过改进模型或优化方法来缓解循环网络的梯度爆炸和梯度消失问题。” 改为“比较有效的方式 是 通过改进模型或优化方法来缓解循环网络的梯度爆炸和梯度消失问题。”这样读起来更通顺一些;
-[4] 一个不成熟的建议。在第六章中，既出现了“隐藏状态”，又出现了“隐状态”，既有“隐藏层”又有“隐层”，是否统一一下比较好呢？：）

**Comment by xpqiu** [comment]
谢谢，已修正。
