### ISSUE TITLE
描述错误 P202(Chap11)

### ISSUE THREAD

**Issue by wen-liao** [nndl/nndl.github.io#147]
公式(11.30)下一段：假设每个变量......需要K^2×4次乘法。
似乎应该为K^2×3次？

公式(11.33)
公式似乎是错的，x1没有完全被消除

**Comment by xpqiu** [comment]
已修正，谢谢。

**Comment by xpqiu** [comment]
再次谢谢，如果方便可以留下您的名字，我会在书中致谢。

**Comment by wen-liao** [comment]
廖文

**Comment by wen-liao** [comment]
另外
公式(15.27)
跳层连接时拼接的特征似乎应该是h'而不是e_t？
