### ISSUE TITLE
描述错误 网络优化与正则化P141 按值截断

### ISSUE THREAD

**Issue by Ison-Laihus** [nndl/nndl.github.io#148]
#描述错误+网络优化与正则化P141

按值截断：在第t次迭代时，梯度为gt，给定一个区间[a, b]，如果一个参数的梯度小于a时，就将其设为a；如果小于b时，就将其设为b。

这里应该是小于a时设置为a，大于b值时设置为b

**Comment by xpqiu** [comment]
已修正，谢谢。
