### ISSUE TITLE
ch3 p36

### ISSUE THREAD

**Issue by shuiaiai** [nndl/nndl.github.io#15]
过拟合的标准定义为：给定一个假设空间H，一个假设h 属于H，如果存在其他的假设h
属于H, 使得在训练样例上h 的损失比h 小，但在整个实例分布上h 比h 的损失
小，那么就说假设h 过度拟合训练数据[?]。

----------
这里h应该是两个不同的概念，能否用不同的标识，否则容易造成误解

**Comment by xpqiu** [comment]
已修改！多谢。如果方便的话可否告诉我你的名字，我在书中正式致谢：）
