### ISSUE TITLE
附录：数学基础，399-400页内容错误

### ISSUE THREAD

**Issue by yingkaisha** [nndl/nndl.github.io#152]
399页边缘部分：
“在支持向量机中，平方指数核函数也叫高斯核函数或高斯我们将GP的均值设置为0——它们实际上已经足够强大，可以在不改变均值的情况下拟合各种函数。径向基函数。这里为了避免混淆，我们称为平方指数核函数。”

疑似为：“平方指数核函数也叫高斯核函数或径向基核函数”

另“它们实际上已经足够强大，可以在不改变均值的情况下拟合各种函数”

更合理的解读为：“0均值高斯过程先验可解得非0均值的高斯过程后验，因此在先验中考虑非0均值通常不是必要的（除非使用者通过其它方法得到了更优的均值估计）。”

另该节存在多处不影响阅读的打字和标点错误。

**Comment by xpqiu** [comment]
谢谢，已修正。

**Comment by xpqiu** [comment]
再次谢谢，如果方便可以留下您的名字，我会在书中致谢。

**Comment by yingkaisha** [comment]
沙颖凯 yingkai@eoas.ubc.ca
