### ISSUE TITLE
typo P139、P372、P373、P374

### ISSUE THREAD

**Issue by RenShuhuai-Andy** [nndl/nndl.github.io#160]
#typo P139
公式(6.12)上一行的【b1】应改为【b】

#typo P372
公式(A.27)往上第三行，“两个【句子】的乘积”应该为“两个【句子】的乘积”

#typo P373
第四行行首 【对角矩阵】应为【单位矩阵】
公式(A.33)及其下一行 xTAx 中的第二个x应为向量形式而非标量形式

#typo P374
公式(A.36)下一行“其中U和V分别为m*m和n*n的正交矩阵”中，n*n漏写
公式(A.37)下一行“其每一列都为A的特征向量，∧为对角阵”中，∧漏写

**Comment by xpqiu** [comment]
已修正，谢谢。
