### ISSUE TITLE
描述不清 P13

### ISSUE THREAD

**Issue by J-cabin** [nndl/nndl.github.io#162]
#问题描述+页号或公式号
-描述不清。13页第4段。“Geoffrey Hinton 等人将引入到多层感知器”，并没有说引入的是什么。结合上下文，应该改成“Geoffrey Hinton 等人将反向传播算法引入到多层感知器”？
-排版问题。15页最后一段。右侧文字溢出。

**Comment by xpqiu** [comment]
谢谢，已修正。
