### ISSUE TITLE
表述错误 P39页

### ISSUE THREAD

**Issue by Andy1314Chen** [nndl/nndl.github.io#164]
P39页笔误？

![image](https://user-images.githubusercontent.com/18392483/55712562-8c8d4580-5a21-11e9-8d6b-3bcf1df3e419.png)

应该是 **使得行列式不为0**，则矩阵非奇异或矩阵满秩，可以使用最小二乘法进行估计。

P51页排版问题

![image](https://user-images.githubusercontent.com/18392483/55723056-8a83b080-5a3a-11e9-8606-eb9bf7380988.png)

**Comment by xpqiu** [comment]
谢谢，已修正。
