### ISSUE TITLE
Typo of Ch12 (词嵌入与语言模型)

### ISSUE THREAD

**Issue by ShangruZhong** [nndl/nndl.github.io#17]
page 161：公式12.31上方，”词汇表V中的每个词……出现的概率“，k的右边少了小于等于号$\leq$。

page 163：底部（”输出层“那一段，公式12.39上方），”其接受的输入为历史信息的向量表示$h_t\mathbb{R}^{d_2}$"，h_t后面少了 \in 。

**Comment by xpqiu** [comment]
已修正，谢谢。
