### ISSUE TITLE
#p21神经网络和深度学习关系的论述

### ISSUE THREAD

**Issue by MasterSongM** [nndl/nndl.github.io#170]
> 套用马克思的一句名言“金银天然不是货币，但货币天然是金银”，我们可以说，深度学习天然不是神经网络，但神经网络天然是深度学习。

个人理解上有点疑惑：
1、金银具有货币的属性，但并非生而为货币；是人们对于“货币”的需要和开发，才使得金银成为典型的货币，且一度成为货币的基础；
2、神经网络并非是为了深度学习设计的，但其契合深度学习（更广泛地讲，从数据中学习一个“深度模型”）的先天需要，因而顺理成章地成为深度学习的基础。
3、上面两点是阅读第一章绪论的理解，那么对应总结时，是否应该说“_神经网络天然不是深度学习，但深度学习天然是神经网络_”呢？意即深度学习可以有神经网络以外的方法，正如货币可以有金银以外的形式；神经网络可以有深度学习以外的领域，正如金银可以有货币以外的应用。

**Comment by MasterSongM** [comment]
不知道上述理解是否正确？（both马克思的话and老师的话）

**Comment by MasterSongM** [comment]
那么据此而言，书中此处的类比表述并不十分恰当……不知道上述理解是否正确？若有不对之处望指正。（both马克思的话and老师的话）

**Comment by xpqiu** [comment]
你好，抱歉回复晚了。谢谢你的建议。
最近也一直在考虑这个问题，我会在最新版修正下。
