### ISSUE TITLE
少打了一个字+9页+1.1.2节

### ISSUE THREAD

**Issue by laicel** [nndl/nndl.github.io#174]
#少打了一个字+9页+1.1.2节

-[]目前我们对人类智能机理论依然知之甚少，少了个论。
-[]
![image](https://user-images.githubusercontent.com/47970735/55786709-60d49300-5ae7-11e9-8e48-02de532b9b62.png)

第一次使用GitHub，不知道能不能成功发出评论。

**Comment by xpqiu** [comment]
应该没错，加了个‘的’，谢谢。
