### ISSUE TITLE
#chap-数学基础.pdf P369 (A.1.3 范数) ℓ2范数 概念说明部分文字漏打

### ISSUE THREAD

**Issue by ydrcg** [nndl/nndl.github.io#178]
chap-数学基础.pdf - 第369页（A.1.3 范数）

ℓ2范数 概念说明部分文字漏打：
“ℓ2范数为向量的各个元素的平方和再开平方。”
![20190410033746](https://user-images.githubusercontent.com/20504258/55829838-35cb5d00-5b42-11e9-96b0-32cf582d661f.png)

**Comment by xpqiu** [comment]
已修正，谢谢。
