### ISSUE TITLE
附录：数学基础，400页表B.1内容不严谨

### ISSUE THREAD

**Issue by ATMsbrother** [nndl/nndl.github.io#182]
#问题描述+页号或公式号
附录：数学基础，400页表B.1里面的对数函数直接写的是f(x) = log(x)，导数是f ′(x) = x1，应该把log(x)改为ln(x)，或者说以a为底的X的对数的导数是1/xlna，以e为底的是1/x
-[]

**Comment by GH1995** [comment]
$\log$ 和 $\ln$ 的写法承袭[Donald E.Knuath](https://www-cs-faculty.stanford.edu/~knuth/taocp.html) 的写法，与[花书](https://www.deeplearningbook.org/)也吻合，属于计算机行业人员约定写法。没有更改的必要。
@xpqiu
