### ISSUE TITLE
long term dependency 建议翻译为 “长程依赖”

### ISSUE THREAD

**Issue by chuangfengwang** [nndl/nndl.github.io#186]
深感邱老师此书对于统一中文术语的重要意义,贡献点绵薄之力

**Comment by J-cabin** [comment]
我觉得翻译成长期依赖、长距离依赖、长依赖都没毛病。毕竟LSTM都是公认翻译成长短期记忆了。

**Comment by xpqiu** [comment]
谢谢建议，就像@j-cabin所说，为了和LSTM一直，这里就引入新的词了。

**Comment by xpqiu** [comment]
谢谢建议，就像@J-cabin所说，为了和LSTM一直，这里就不引入新的词了。

**Comment by chuangfengwang** [comment]
印象中,大家提到“长短期记忆模型”的时候,会直接说LSTM,一个"领域问题"没必要和一个专有模型保持一致. 而 long term dependency 翻译成“长期依赖”会给人一种“这是个时间问题”的错觉. 后来者进入这个领域的时候,前辈和各种教材就要反复强调,这和时间无关,只是个翻译问题. 考虑到每年数万新人进入这个领域,一个合适的命名就可以节省巨大的社会成本,这对进一步推广DL是很有好处的呀.

**Comment by xpqiu** [comment]
我最后还是采用你的建议，谢谢。
