### ISSUE TITLE
打字/排版错误 第七章

### ISSUE THREAD

**Issue by kadoufall** [nndl/nndl.github.io#190]
# 打字/排版错误 第七章

2019.04.10版
- [x] 172页 7.2.3.3小标题 `"AdaM算法"` 中的字母 "M" 应是小写
- [x] 184页 左下角旁注溢出
- [x] 186页 左下角旁注有遮盖
- [x] 194页 习题7-2，两个公式显示为 `"(??)"`

**Comment by xpqiu** [comment]
已修正，谢谢。
