### ISSUE TITLE
第四章-前馈神经网络-90页-4.2.1-对前馈神经网络描述有疑问

### ISSUE THREAD

**Issue by SC-ZTP** [nndl/nndl.github.io#192]
-[问题]
4.2.1节描述前馈神经网络有一句：整个网络中的信息是朝一个方向传播，没有反向的信息传播，可以用一个有向无环路图表示。
-[疑问]
当使用BP学习算法学习时，信息不是往后传播了吗？
我又翻了周志华老师的《机器学习》第五章神经网络，在描述前馈神经网络时，旁边的注脚提到了：“前馈”并不意味着网络中的信号不能向后传，而是指网络拓扑结构上不存在环或回路。

**Comment by xpqiu** [comment]
描述应该没有问题。
