### ISSUE TITLE
Inception v4模型描述有误 5.4.3节/P130

### ISSUE THREAD

**Issue by yunkchen** [nndl/nndl.github.io#195]
#5.4.3对Inception v4的描述存在偏颇（P130）

-[此外，Szegedy et al. [2017]还提出了结合直连(Shortcut Connect)边的 Inception模块:Inception-ResNet v2网络，并在此基础上并设计了一个更优化 的Inception v4模型。]
-[此外，Szegedy et al. [2017]还提出了结合直连(Shortcut Connect)边的 Inception模块:Inception-ResNet v2网络，同时在原来Inception v3的基础上设计了一个更优化 的Inception v4模型。]

**Comment by xpqiu** [comment]
已删除。
