### ISSUE TITLE
第五章-一维卷积计算错误

### ISSUE THREAD

**Issue by EngineerFan** [nndl/nndl.github.io#196]
#问题描述+页号或公式号
一维卷积demo计算错误  页码：111   如图所示：
-[]
-[]
![image](https://user-images.githubusercontent.com/26210757/56029189-739bd180-5d4c-11e9-96d7-f224da77ff3f.png)

**Comment by jswanglp** [comment]
文中假设滤波器参数为[-1, 0, 1]，卷积运算本来就是翻转的，所以应该是 [1, -2, -2, 1, 1, 1, 0]。

**Comment by jswanglp** [comment]
> #问题描述+页号或公式号
> 一维卷积demo计算错误 页码：111 如图所示：
> -[]
> -[]
> ![image](https://user-images.githubusercontent.com/26210757/56029189-739bd180-5d4c-11e9-96d7-f224da77ff3f.png)

文中假设滤波器参数为[-1, 0, 1]，卷积运算本来就是翻转的，所以应该是 [1, -2, -2, 1, 1, 1, 0]。

**Comment by jswanglp** [comment]
> #问题描述+页号或公式号
> 一维卷积demo计算错误 页码：111 如图所示：
> -[]
> -[]
> ![image](https://user-images.githubusercontent.com/26210757/56029189-739bd180-5d4c-11e9-96d7-f224da77ff3f.png)

文中假设滤波器参数为[-1, 0, 1]，卷积运算本来就是翻转的，所以应该是 [1, -2, -2, 1, 1, 1, 0]。这章对应的 PPT 上也存在相同的错误，而且 PPT 与书中的卷积结果也不一样。

**Comment by jswanglp** [comment]
> #问题描述+页号或公式号
> 一维卷积demo计算错误 页码：111 如图所示：
> -[]
> -[]
> ![image](https://user-images.githubusercontent.com/26210757/56029189-739bd180-5d4c-11e9-96d7-f224da77ff3f.png)

你看卷积权重连接的情况，你理解错了，原序列是 [1, 1, 2, -1, 1, -2, 1]，卷积核是 [-1, 0, 1]，valid 模式，结果就是 [-1, 2, 1, 1, 0]。

**Comment by EngineerFan** [comment]
OK的

**Comment by GH1995** [comment]
@xpqiu 问题已解决，建议关闭 issue
