### ISSUE TITLE
第五章的一些疑惑

### ISSUE THREAD

**Issue by xdyuchen** [nndl/nndl.github.io#198]
# 阅读 《神经网络与深度学习》 第五章的一些疑惑

- P115 图5.1 貌似是对一维序列做 [1,0,-1] 的卷积 与上文做 [-1,0,1] 做卷积不符
- P115 图5.2 左侧矩阵右下侧蓝色的计算卷积矩阵与公式右侧的卷积不同（计算需要翻转吗，按5.6的公式是不需要的）
- P127 Line 5 60个5X5的滤波器 -> 16个5X5的滤波器
- P114 最后一行，感觉计算公式写成 (n+2p-m)/s+1 比较直观（个人理解）
- P120 关于权重共享可以解释下每一个卷积核在一个固定权重（学习得来）下仅对一种数据特征激活，在一个卷积层中通过设置（超参数）多个卷积核去捕获多种数据特征，当时看到这里时不是很理解权重共享，查资料才理解的
- P129 Line 3 第三个卷积层为两个路径的融合，使用一个3X3X256X384的卷积核 不很理解，从图上看 仍是使用两个3X3X128X196的卷积在两个GPU上训练

只是自己看到有疑惑的地方，或许有误，见谅

**Comment by williamcheng-web** [comment]
图5.2是需要翻转的，但是对公式5.6有些困惑，和之前见到的卷积运算不太一样，对于这个公式按照图示也不太理解，望大佬解答，谢谢

**Comment by xpqiu** [comment]
公式5.6是需要翻转的，两个X和W中下标uv的符号相反。

**Comment by williamcheng-web** [comment]
谢谢老师的答复，不知老师是否方便说明下在W,X,Y中的坐标系，谢谢
