### ISSUE TITLE
can we get those PDF in  English language also much appreciated 

### ISSUE THREAD

**Issue by RahulJyala7** [nndl/nndl.github.io#200]
#问题描述+页号或公式号

-[]
-[]

**Comment by RahulJyala7** [comment]
所有的pdf都是中文的，所以也不能告訴你問題陳述

**Comment by GH1995** [comment]
I suggest you get the legal authorization from @xpqiu , and then you can organize volunteers to translate the book.

**Comment by GH1995** [comment]
suggest close #200
