### ISSUE TITLE
第一章 绪论 第1.2.3节 page11 语句错误

### ISSUE THREAD

**Issue by yqwung** [nndl/nndl.github.io#201]
第1.2.3节 第四阶段 流行度降低 
“虽然神经网络可以很容易地增加层数、神经元数量，而从构建复杂的网络，但其计算复杂性也会指数级增长。” 中的 “而从”应该改为“从而”

**Comment by Alan-Lee123** [comment]
"计算复杂性也会指数级增长"。 指数级增长应该应该是个错误的论断。神经网络的层数神经元数量带来的计算量增长应该是多项式级别的。

**Comment by xpqiu** [comment]
已修正，谢谢。
