### ISSUE TITLE
第一章 绪论

### ISSUE THREAD

**Issue by yqwung** [nndl/nndl.github.io#203]
- 第1.4.1节 page14
“**相比与**局部表示，分布式表示的表示能力要比局部表示强很多”建议改为“**相比**局部表示，分布式表示的表示能力要比局部表示强很多”
- 第1.5节 page15
“为了学习一种好的表示，需要构建具有一定“深度”的模型，并通过学习算法**来让**模型**来**自动学习出好的特征表示”建议改为“为了学习一种好的表示，需要构建具有一定“深度”的模型，并通过学习算法**来让**模型自动学习出好的特征表示”
- 第1.6节 page19
“第13章和第15章**分布**介绍两种概率生成模型：深度生成模型和序列生成模型。”建议改为“第13章和第15章**分别**介绍两种概率生成模型：深度生成模型和序列生成模型。”
“每章最后一节都提供了一些参考文献，读者**度**需要通过深入阅读来了解这些知识。”建议改为“每章最后一节都提供了一些参考文献，读者**都**需要通过深入阅读来了解这些知识。”
- 第1.7节 page19
“如何自动学习有效的数据表示**是成为**机器学习中的关键问题。”建议改为“如何自动学习有效的数据表示**是**机器学习中的关键问题。”

**Comment by xpqiu** [comment]
已修正，谢谢。
