### ISSUE TITLE
编注遮挡问题 Page 51 & 184

### ISSUE THREAD

**Issue by GH1995** [nndl/nndl.github.io#208]
# 编注遮挡问题+Page 51

![image](https://user-images.githubusercontent.com/11362493/56128344-eeb1f180-5fb1-11e9-8738-d0028e97d112.png)

**Comment by GH1995** [comment]
Page 184 编注遮挡问题
![image](https://user-images.githubusercontent.com/11362493/56185194-65e99300-604f-11e9-9073-e02daea9bf87.png)

**Comment by xpqiu** [comment]
已修正，谢谢。
