### ISSUE TITLE
ch2中公式2.67

### ISSUE THREAD

**Issue by notxyz27** [nndl/nndl.github.io#21]
公式2.67typo，以及描述出现两次公式2.65

**Comment by tigerneil** [comment]
Thanks for pointing out the mistake. I will fix it later.

Xiaohu

Chen Chen <notifications@github.com>于2017年3月16日周四 上午12:11写道：

**Comment by xpqiu** [comment]
请问下目前最新版本中对应哪个公式？

**Comment by notxyz27** [comment]
新版第二章19页，“通过公式2.66和2.66.......” 应该是 2.66和2.67？ 以及下面的公式2.68

**Comment by xpqiu** [comment]
已修正，如果方便的话可否告诉我你的名字，我在书中正式致谢：）
