### ISSUE TITLE
文本更正建议 Page75

### ISSUE THREAD

**Issue by GH1995** [nndl/nndl.github.io#210]
![image](https://user-images.githubusercontent.com/11362493/56131106-28d2c180-5fb9-11e9-9a52-985f8fae2a2c.png)

前述已经说了λ计算不易，简略提到使用SMO等算法。故下一段不应使用**再**字，因为并没有计算出，容易使学生产生误解。

怀疑是笔误，应使用**在**字，表示当计算出λ的值时，我们可以往后推导支持向量。

**Comment by xpqiu** [comment]
已修正，谢谢。
