### ISSUE TITLE
# 深度强化学习相关typo

### ISSUE THREAD

**Issue by HazekiahWon** [nndl/nndl.github.io#212]
# 深度强化学习相关typo
## p335
- [在强化学习中的基本要素]
强化学习 （在 去掉，语病）
## p336
- 马尔可夫性
马尔可夫性质（Markov Property）
## p337
- 持续性强化学习
术语对应的英文？
## p338
- 一个策略\pi期望回报
策略\pi的期望回报
## p343
- 在似估计出Q函数
近似估计
## p344
- on policy
on-policy
- off policy
off-policy
## p347
- 如果采样时序差分方法
采用
## p348
- 经验池
术语对应英文？（replay buffer?）
- 随机从经验池中抽取样本来来代替
去掉一个来
- 算法14.5
C应该是一个超参数，应该放在输入里？
## p350
- 算法14.6
T应该是一个超参数，应该放在输入里？
\theta收敛这种说法比较奇怪？也许写\pi_\theta会更明确
## p353
- 策略函数\pi_\theta(s,a)
要么写\pi_\theta(s)要么写\pi_\theta(a|s)
\pi不应该同时是s,a的函数
- 基函数
基线函数（baseline）
否侧会误解成basis function

**Comment by feiyue1230** [comment]
p341

**Comment by feiyue1230** [comment]
很赞邱老师的分享！
弱弱说一句  p341
14.1.5.3   前后两个\pi(a|s)是不含义不同，符号上是不是需要区分下；或者后者直接写为具体概率

**Comment by GH1995** [comment]
@HazekiahWon 建议修改一下公式，用[MathJax](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima)显示不全

**Comment by xpqiu** [comment]
谢谢已修正。
