### ISSUE TITLE
chapter4_Page95_4.40

### ISSUE THREAD

**Issue by Amazingren** [nndl/nndl.github.io#213]
#问题描述+页号或公式号
第四章  95页   4.40和4.41一模一样，是不是重复了？
-[]
-[]

**Comment by GH1995** [comment]
用的是4月12日的版本，Page 95并没有公式4.40。在Page 99上确实出现的这个问题 @xpqiu，截图如下
![image](https://user-images.githubusercontent.com/11362493/56186190-2e7be600-6051-11e9-9988-204c0f35fca9.png)

**Comment by xpqiu** [comment]
已修正，谢谢。
