### ISSUE TITLE
GRU图例解释不清 Page156

### ISSUE THREAD

**Issue by GH1995** [nndl/nndl.github.io#215]
原图使用的是【如下】，图例过于繁琐
![image](https://user-images.githubusercontent.com/11362493/56179413-3c713d00-6038-11e9-9d31-034164d358b4.png)

建议简化为类似这样的图
![image](https://user-images.githubusercontent.com/11362493/56179454-5f035600-6038-11e9-9592-6b4c36607211.png)

[Wikipedia GRU](https://www.wikiwand.com/en/Gated_recurrent_unit)

**Comment by xpqiu** [comment]
嗯，简化了下。谢谢建议。

**Comment by GH1995** [comment]
谢谢邱老师
