### ISSUE TITLE
标题编号问题 Page 176

### ISSUE THREAD

**Issue by GH1995** [nndl/nndl.github.io#217]
此节的编号是否需要改变？

![image](https://user-images.githubusercontent.com/11362493/56185921-72bab680-6050-11e9-8e6c-806ee378911f.png)

**Comment by GH1995** [comment]
如觉得该小节内容较为单薄，不宜使用三级标号，请予以说明，避免读者误解

**Comment by xpqiu** [comment]
已修正，谢谢。
