### ISSUE TITLE
ch5的5.4(87页)

### ISSUE THREAD

**Issue by daokouer** [nndl/nndl.github.io#22]
> Theano [Bergstra et al., 2010]和Tensorflow [Abadi et al., 2016]都采用了符号微分的方法进行自动求解梯度。

该说法有误. Theano和Tensorflow均采用反向模式自动微分 (Reverse-mode Automatic Differentiation), 相关内容可参考: [1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients_impl.py#L455), [2](http://deeplearning.net/software/theano/tutorial/gradients.html), [3](http://stackoverflow.com/a/39082247), [4](http://stackoverflow.com/a/36373220).

**Comment by xpqiu** [comment]
http://deeplearning.net/software/theano/tutorial/gradients.html 这里描述，theano是符号微分。that we are computing the correct symbolic gradient.

**Comment by daokouer** [comment]
theano开发者本身用词的误导，其实看具体内容的话，跟本书中的自动微分是一样的，其给的wiki参考链接也是automatic differentiation。

**Comment by xpqiu** [comment]
多谢了，已修正。
