### ISSUE TITLE
激励函数改为激活函数更合适(Page11)

### ISSUE THREAD

**Issue by xung** [nndl/nndl.github.io#225]
第11页, **1.2.2 人工神经网络** 章节内:
>每个节点代表一种特定函数，来自其他节点的
信息经过其相应的权重综合计算，输入到一个激励函数中并得到一个新的活性
值（兴奋或抑制）。

其中`激励函数`改为`激活函数`更合适.  一方面更符合日常说法, 另外也可与书中其它地方保持一致(全书其它地方都是使用激活函数).

**Comment by xpqiu** [comment]
已修正，谢谢。
