### ISSUE TITLE
第七章 网络优化与正则化公式计算负梯度公式的问题

### ISSUE THREAD

**Issue by jswanglp** [nndl/nndl.github.io#228]
# 示意图不妥 - 168 页中 7.2.3.3 小节
- **167** 页中定义了 $ \Delta \theta _{t}$ 为 **负梯度** ，这样的话位于 **168** 页的图 **7.4** 的矢量相加示意图是不是不太妥当，如果它是 **正梯度**，则去掉学习率 $\alpha$ 前的 `-` 号比较合理。
- **164** 页最后一段文字中 "每次迭代选取的批量样本数越多，**下降效果越明显**"，不同 batchsize 下完成一次迭代的时间不一样，这样通过迭代次数来判别下降效果的明显与否是不是不太合适？

**Comment by xpqiu** [comment]
谢谢建议。感觉上这两点没有什么不妥：）
