### ISSUE TITLE
关于ch1的部分typo

### ISSUE THREAD

**Issue by Kouei** [nndl/nndl.github.io#23]
第三页：
【智能系统如何外部刺激信息（视觉和语音等）进行感知和加工】应为
【智能系统如何**对**外部刺激信息（视觉和语音等）进行感知和加工】
第八页：
【Kunihiko Fukishima(福岛邦彦）】应为：
【Kunihiko **Fukushima**(福岛邦彦）】

**Comment by xpqiu** [comment]
多谢！已更正。
