### ISSUE TITLE
推导过程 Page 285

### ISSUE THREAD

**Issue by GH1995** [nndl/nndl.github.io#232]
- [ ] 能否在公式`11.87~11.89`之间给出更详细的推导过程

![image](https://user-images.githubusercontent.com/11362493/56364538-5b7ef300-6221-11e9-8eff-b4ae6eb0eee1.png)

**Comment by xpqiu** [comment]
这个是jensen不等式的直接应用。

**Comment by GH1995** [comment]
好的
