### ISSUE TITLE
句子表述不清 - 39页

### ISSUE THREAD

**Issue by liangyihuai** [nndl/nndl.github.io#234]
# 句子表述不清 - 39页

## 位置：

“ 2.3.1.3 最大似然估计”段落的下面第五行。

## 目标句子：
“其服从以均值为f(x,w) = w T x为中心”

## 问题：
该句子存在两个“为”子，使得整个句子表述不清，意思不明确。谢谢

**Comment by xpqiu** [comment]
谢谢，已修正。
