### ISSUE TITLE
第8章 P195 句子不通顺  

### ISSUE THREAD

**Issue by LeLiu** [nndl/nndl.github.io#235]
# P195 
- [ ] 第2段，倒数第3行，**来行得通**，**来**字多余
- [ ] 第2段中的阅读理解例子这块，文本分类任务的例子夹在了对阅读理解任务描述的两段中间，读起来很不顺
- [ ] 第3段**一般来，利用一组神经元存储信息的容量和**可改为**一般来讲，神经网络利用一组神经元来存数信息，网络**
- [ ] 第4段第3行，**来源于**可以去掉

**Comment by xpqiu** [comment]
谢谢，已修正。
