### ISSUE TITLE
第8章 8.1 P196 语句不通顺

### ISSUE THREAD

**Issue by LeLiu** [nndl/nndl.github.io#236]
# P196 8.1

- [ ]  8.1 **注意力机制是解决信息超载的主要手段的一种分配方案，将计算资源分配给更重要的任务”**，**手段的方案**感觉很别扭，可否改为类似**注意力机制作为一种分配方案，将计算资源分配给更重要的任务，是是解决信息超载的主要手段** 这个句子**注意力是手段**的表述放在段首貌似比较合适
- [ ]  8.1.1 第1段，第3行，**可以**去掉，**还能**放在**可以**的位置顺一些
- [ ]  8.1.1 第1段，倒数第2行，两个**体现在**改为**作用在**好像更好
- [ ]  8.1.1 第2段，第3行，**显著性**应该用楷体，后边的**的**可以去掉和后文保持一致

**Comment by xpqiu** [comment]
谢谢，已修正。
