### ISSUE TITLE
第8章 P197 表述模糊

### ISSUE THREAD

**Issue by LeLiu** [nndl/nndl.github.io#237]
# 8.1.2 

- [ ] 第2段，**X = [x1, · · · , xN ]表示N 个输入信息**，是否是**一个N维的输入**比较符合习惯
- [x] 第2段，第一句话重复，**计算资源**和**进行计算**重复，第3行的**给神经网络**感觉也有些重复
- [ ] **查询向量q**和**注意力打分函数**出现感觉比较突兀，如果不太了解注意力机制还是读的不太懂，可否先进行说明

**Comment by xpqiu** [comment]
谢谢，已修正。
