### ISSUE TITLE
句子问题 + 第3章 第66页 

### ISSUE THREAD

**Issue by liangyihuai** [nndl/nndl.github.io#244]
## 1. 位置
第3章 第66页 ， **段落3.4.1 参数学习** 的下面第2和3行，

## 目标句子：

感知器试图学习感知器试图学习到参数w ∗ 

## 问题： 

词语重复， “感知器试图” 重复

## 建议：
把“感知器试图学习感知器试图学习到参数w ∗ ”改为“学习感知器试图学习到参数w ∗ ”。谢谢

**Comment by xpqiu** [comment]
谢谢，已修正。
