### ISSUE TITLE
表述不全面 + 第三章，page 61

### ISSUE THREAD

**Issue by liangyihuai** [nndl/nndl.github.io#245]
## 1. 位置
第三章，page 61， **公式（3.17）**上面一句话

## 2目标句子：
将公式 (3.14)进行变换后得到

## 3问题：
表述不全面， 公式（3.17）是由公式 (3.14)和公式 (3.16)两个变换的结果，所以给出下面建议：

## 4建议：
将目标句子“**将公式 (3.14)进行变换后得到**”改为“将公式 (3.14)和 **(3.16)** 进行变换后得到”。谢谢

**Comment by xpqiu** [comment]
谢谢，应该没有问题。
