### ISSUE TITLE
公式错误  第4章 99页

### ISSUE THREAD

**Issue by liangyihuai** [nndl/nndl.github.io#246]
## 1. 位置
第4章 99页， 公式4.42和公式4.44

## 2 问题：
公式等号=两边的上标小括号里面的l 不应该相等，因为等号两边的W表示不同的网络层的参数。

## 3建议：
等号左边保持不变，等号右边上标小括号中的l改为（l-1），谢谢

**Comment by xpqiu** [comment]
？不明白什么意思。
