### ISSUE TITLE
句子表述问题 第4章107页

### ISSUE THREAD

**Issue by liangyihuai** [nndl/nndl.github.io#247]
## 1. 位置
第4章107页，段落**4.6.1 非凸优化问题** 下面一句话

## 2目标句子：
以一个最简单的1-1-1结构的2层神经网络为例来其损失函数与参数的可视化例子。

## 3问题：
读起来不通顺

## 4建议：
根据作者的本人想要表达的意思来修改，谢谢

**Comment by xpqiu** [comment]
谢谢，已修正。
