### ISSUE TITLE
句子表述问题 + 第5章113页

### ISSUE THREAD

**Issue by liangyihuai** [nndl/nndl.github.io#248]
## 1. 位置
第5章113页，
## 2 目标段落：

**（2）局部不变性特征**：自然图像中的物体都具有局部不变性特征，比如在
尺度缩放、平移、旋转等操作不影响其语义信息。而全连接前馈网络很难提取
这些局部不变特征，一般需要进行数据增强来提高性能。

## 3 目标句子：
比如在尺度缩放、平移、旋转等操作不影响其语义信息。

## 3问题：
表述问题，“在”跟“的什么时候”搭配，而句子中没有“的时候”。

## 4建议：
把“在”字去掉，目标句子变成“比如尺度缩放、平移、旋转等操作不影响其语义信息。”谢谢

**Comment by xpqiu** [comment]
谢谢，已修正。
