### ISSUE TITLE
表述错误 第5章 121页

### ISSUE THREAD

**Issue by liangyihuai** [nndl/nndl.github.io#250]
## 1. 位置
第5章 121页，倒数第2行

## 2目标句子：
每一个输入特征映射都需要D个滤波器以及一个偏置。

## 3问题阐述：
根据 **“输入为X ∈ R M×N×D ，输出为Y ∈ R M ×N  ×P的卷积层”**，D被理解为第l层输入的“图片”的通道个数，P被理解为第l层输出的“图片”通道个数。在该层所需要的滤波器的个数为P。每一个滤波器都是一个（m，n，D）三维的（结合图5.6来理解），所以，目标句子中的D应该改为P

## 4建议：
目标句子中的D应该改为P，（如果作者在此处想表达的是每一个输入特征有D个“通道”，所以有D个滤波器，依然把滤波器考虑成2维的，而不是3维的，是不是有点不恰当了呢？）谢谢

**Comment by xpqiu** [comment]
谢谢，已修正。
