### ISSUE TITLE
第十三章 深度生成模型 KL 散度公式疑惑

### ISSUE THREAD

**Issue by jswanglp** [nndl/nndl.github.io#259]
## 求两个正态分布的 KL 散度公式，318页公式（13.25）和（13.26）

- [x] 缺少对公式中参数 `k` 的描述，应该是隐变量 **z** 的维度吧。
- [ ] 对数运算符 `log` 的使用：公式前项均是通过对自然底数 `e` 求对数所得，所以这一项是不是写成自然对数符号 ln\frac{\left|\sum_{2}\right|}{\left|\sum_{1}\right|} 更加严谨些。

**Comment by xpqiu** [comment]
谢谢，已修正。
本书默认log以e为底。
