### ISSUE TITLE
公式错误+公式14.37

### ISSUE THREAD

**Issue by tangbotony** [nndl/nndl.github.io#260]
#公式错误+公式14.37
- [ ] 推导错误：P345公式14.37中推导错误
G(τs0=s,a0=a,s1=s′,a1=a′ ) = r(s, a, s′) + γG(τs0=s′,a0=a′ )
下标错误，应该是：
G(τs0=s,a0=a,s1=s′,a1=a′ ) = r(s, a, s′) + γG(τs1=s′,a1=a′ )

**Comment by xpqiu** [comment]
这里的意思是将(τs0=s′,a0=a′ )看作是一个新的轨迹。
