### ISSUE TITLE
第7章 循环神经网络中问题

### ISSUE THREAD

**Issue by Guohai93** [nndl/nndl.github.io#27]
- 第2页，图7.1下面第5行，“也**成为**长期依赖问题”，应该是“也**称为**长期依赖问题”

- 第4页，公式(7.6)中字母y是否应该解释一下，突然冒出有点唐突

- 第7页，图7.4 LSTM结构示例，建议更详细地叙述一下图中信息流动的过程，结合三个门作用，step by step阐述比较好（建议参考http://colah.github.io/posts/2015-08-Understanding-LSTMs/）

**Comment by xpqiu** [comment]
感谢建议，已修正。第三个问题以后再改！如果方便的话可否告诉我你的名字，我在书中正式致谢：）

**Comment by Guohai93** [comment]
谢谢邱老师书写这么棒的书，我是华东师范大学徐国海，我会持续关注您的书^_^
