### ISSUE TITLE
错别字+P345 公式13.51

### ISSUE THREAD

**Issue by dyf0631** [nndl/nndl.github.io#270]
# 问题描述（例如：错别字） + 页号或公式号

- [1 ] 错别字：P345 公式13.51 中 $P_{g}$ 改为 $P_{\theta}$.
- [ 2] 错别字：P345 公式13.51下一行， 其中 Γ(pr , pθ ) 改为 $\Pi\left(P_{r}, P_{\theta}\right)$.

**Comment by xpqiu** [comment]
谢谢，已修正。
