### ISSUE TITLE
错别字 + 第五章130页

### ISSUE THREAD

**Issue by Pengyang233** [nndl/nndl.github.io#271]
5.4.4 残差网络  上面那一段的上面两行，原文”称为， Inception v3...“应该改为"此外"

**Comment by Pengyang233** [comment]
另外还有一个问题，第五章P121，公式(5.20)上面一行，“b得到卷积层的净输入Z^p”，为什么是净输入？个人理解**X**是输入，**W**为权重，Z为卷积净输出，随后经过激活函数。
不知我的理解是否有问题？

**Comment by xpqiu** [comment]
谢谢，已修正。
这里\myemp{净输入}是指没有经过非线性激活函数的净活性值（Net Activation）。
