### ISSUE TITLE
第十三章深度生成模型VAE隐变量可视化的图像问题

### ISSUE THREAD

**Issue by jswanglp** [nndl/nndl.github.io#272]
## 324页中图13.5中(a)图与(b)图的对应关系没有体现出来

- [ ] ：建议在 **图(b)-隐变量 z 在图像空间投影** 的图中加入坐标信息，虽然不是严格的对应关系，但是能够很好的反映出两张图的对应关系，大致如下图所示：

![VAE](https://user-images.githubusercontent.com/29540704/56641261-8c3eac80-66a7-11e9-9904-e0541dfdc42b.jpg)
- [x] 错别字：326页中 “比如，(1)使用 **代** 步长的卷积”，应该修改为 “**带**”。

**Comment by xpqiu** [comment]
谢谢建议。

**Comment by xpqiu** [comment]
最新版已修改：）
