### ISSUE TITLE
114页底，移动平均建议

### ISSUE THREAD

**Issue by JackMaYY** [nndl/nndl.github.io#289]
当滤波器$f_k = 1 / m$, $1 <= k <=m$时，卷积相当于信号序列的移动平均；此处，个人建议应写成：  当滤波器$\bm{w}_k = 1 / m$，1 <=k <= m时，卷积相当于信号序列的移动平均值；此外，应在旁边批注：移动平均值的概念定义及示例。对于一维卷积示例图，个人建议，应在图旁添加说明，例如：信号序列，滤波器，卷积结果，这样能够让无背景知识的同学理解更加清晰、透彻。

**Comment by xpqiu** [comment]
谢谢，已修正。
