### ISSUE TITLE
叙述不清晰+119页

### ISSUE THREAD

**Issue by ShenYounger** [nndl/nndl.github.io#296]
119页叙述错误的是：119页中叙述 “当m和n都很大时，权重矩阵的参数非常多，训练的效率会非常低。“，这里的m和n像天外飞仙一样直接飞进来了，而且下面说“滤波器w(l) ∈ R
m 的卷积”，这里我的理解是卷积核的大小是m。感觉这两个m在定义上是冲突的。

120页叙述错误的是：由于局部连接和权重共享，卷积层的参数只有一个m维的权重w(l) 和1维
的偏置b(l)，共m + 1个参数。这里作者说w(l)是m维、b(l)是1维的。可是在119页，你又分明说b(l)是 ∈ R
n(l)。如果按照你的说法，b(l)是n(l)维的啊。

我不知道我的理解是否有问题？

**Comment by xpqiu** [comment]
谢谢，已修正。
