### ISSUE TITLE
语句不通顺 P39 章节2.3.1.3

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#307]
# 语句不通顺 P39 章节2.3.1.3

- [ ] 在小节开头 “机器学习任务可以分为两类，一类是样本的特征向量 x 和标签 y 之间如果存在未知的函数关系y = h(x)”,这里的“如果”疑似冗余,建议去除.

**Comment by xpqiu** [comment]
谢谢，已修正。
