### ISSUE TITLE
ch06 6.2节末尾表述错误

### ISSUE THREAD

**Issue by ghandzhipeng** [nndl/nndl.github.io#31]
公式6.8中，第l − 1层的所有特征映射都经过滤波器得到一个第l层的
一组特征映射X(l,k)。也就是说，第l 层的每一组特征映射都依赖于第l 层的所
有特征映射，相当于不同层的特征映射之间是全连接的关系。

--> ...应该是“第l 层的每一组特征映射都依赖于第l - 1层的所
有特征映射”...

**Comment by xpqiu** [comment]
感谢指出错误！已修正。如果方便的话可否告诉我你的名字，我在书中正式致谢：）
