### ISSUE TITLE
公式错误 P63注释栏

### ISSUE THREAD

**Issue by Flamealone** [nndl/nndl.github.io#312]
# 公式错误 P63注释栏第一个注释

- [ ] 其中<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{w}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{w}" title="\mathbf{w}" /></a>应该改为 <a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{w^Tx}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{w^Tx}" title="\mathbf{w^Tx}" /></a>正确公式：<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;\hat{y}}{\partial&space;\mathbf{w^Tx}}=\hat{y}^{(n)}\left(1-\hat{y}^{(n)}\right)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;\hat{y}}{\partial&space;\mathbf{w^Tx}}=\hat{y}^{(n)}\left(1-\hat{y}^{(n)}\right)" title="\frac{\partial \hat{y}}{\partial \mathbf{w^Tx}}=\hat{y}^{(n)}\left(1-\hat{y}^{(n)}\right)" /></a>

**Comment by xpqiu** [comment]
谢谢，已修正。
