### ISSUE TITLE
疑似语病 P116 公式5.7下方

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#313]
# 疑似语病 P116 公式5.7下方

- [ ] 语病“互相关和卷积的区别在于卷积核仅仅是否进行翻转”，应该将“仅仅”放到“在于”的前面。

**Comment by xpqiu** [comment]
谢谢，已修正。

**Comment by xpqiu** [comment]
谢谢你提出的多个错误。方便的话，可以留下你的名字，我会在书中致谢。

**Comment by lintongmao** [comment]
邱老师您好，我叫林同茂，很高兴能帮助完善这本书。
