### ISSUE TITLE
#typo chap-数学基础

### ISSUE THREAD

**Issue by RenShuhuai-Andy** [nndl/nndl.github.io#317]
- [x] P395  （A.33）下面一行，半正定阵定义的第二个x应为向量表示
- [ ] P398  雅克比矩阵（B.4）有误，应该为其转置形式
- [ ] P400  按位计算的向量函数及其导数（B.18）f(x_j) 应为 f(x_i)

**Comment by yuyan2680** [comment]
雅可比矩阵的使用感觉有些乱，有的地方用的是附录中的形式，有的地方如(6.43)又用的是转秩的形式，是我算错了么？

**Comment by xpqiu** [comment]
谢谢。
后面两个应该没有问题。6.43是矩阵对标量求导，应该是转置的。见最新版的公式B.6。

**Comment by xpqiu** [comment]
@yuyan2680  6.43是矩阵对标量求导，应该是转置的。见最新版的公式B.6。
