### ISSUE TITLE
Xavier初始化最后一步推导疑似错误 P177 公式7.37上方

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#320]
# Xavier初始化最后一步推导疑似错误 P177 公式7.37上方 

- [ ] 公式7.37上方“并且$\mathrm{var}[w_i^l]=1$”疑似是多余的条件，因为：1. 公式7.35和7.36已经足够导出公式7.37；2. 该条件和公式7.35矛盾：如果$\mathrm{var}[w_i^l]=1$成立，那么$n^{(l-1)} + n^{(l)} = 2$也必定成立，这很违反常理。

**Comment by xpqiu** [comment]
谢谢，已修正。
