### ISSUE TITLE
符号使用重复 + P132

### ISSUE THREAD

**Issue by fuguoji** [nndl/nndl.github.io#322]
# 符号使用重复 + P132

- [ ] 符号使用重复：P132页最后一段“对一个p 维的向量z，和大小为m的卷积核，如果希望通过卷积操作来映射到高维向量，只需要对向量z 进行两端补零p = m− 1，然后进行卷积，可以得到p + m − 1 维的向量。”中符号"p"指代不明，p既指代向量“z”的维度，也指代padding两端补零的个数。

- [ ] 同样的问题出现在P133页倒数第二段。

**Comment by xpqiu** [comment]
谢谢，已修正。
