### ISSUE TITLE
十二章《词嵌入与语言模型》中一些问题

### ISSUE THREAD

**Issue by Guohai93** [nndl/nndl.github.io#33]
我仔细阅读了第十二章的内容，并对绝大部分公式进行了推导，发现以下一些错误（准确说，应该是笔误，细节小问题）

- 第1页，黑体“局部表示”的下一行中“假设有1000中颜色”的“中”，应为“种”

- 公式（12.9）中字母 “i” 有点问题，应直接用“t”

- 公式（12.52）上一行中字母“K”应该为小写"k"，本页倒数第二行也是小写，应统一

- 公式（12.68）上一行中“趋向于无穷大是”中“是”，应改为“时”

- 公式（12.73）至（12.75）中出现的h_{t} 与 h 应统一，有些漏掉下标 t，同理（12.84）至（12.88）中建议检查一下是否需要下标 t

- 第22页，黑体“真实样本”的上2行，句末“是的”，应为“使得”

其实都是一些无关紧要的小细节，如果老师检查后觉得有误就修改一下，非常感谢老师贡献出精彩的写作！供我们学习，谢谢您～

**Comment by xpqiu** [comment]
感谢指出错误！已修正。如果方便的话可否告诉我你的名字，我在书中正式致谢：）

**Comment by Guohai93** [comment]
谢谢邱老师，我是华东师范大学学生徐国海～
