### ISSUE TITLE
下标错误

### ISSUE THREAD

**Issue by XiangqianMa** [nndl/nndl.github.io#338]
# 下标错误 + 100页（公式（4.51）的介绍）
- [ ] 下标错误：P100（第4.4节反向传播算法）公式（4.51）下的一行对该公式的符号进行介绍时，应该是第i个元素为![](http://latex.codecogs.com/gif.latex?\\alpha_j^{(l-1)})，书中为第j个。

**Comment by xpqiu** [comment]
谢谢，已修正。
