### ISSUE TITLE
公式下标歧义 隐马尔可夫模型 P265 公式11.15

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#339]
# 公式下标歧义 隐马尔可夫模型 P265 公式11.15

- [ ] 公式中以<img width="20" alt="屏幕快照 2019-05-24 16 46 35" src="https://user-images.githubusercontent.com/33687938/58315155-87eee600-7e43-11e9-9db5-f119edd767a9.png">表示输出概率的参数，其下标与公式中的时序下标$t$重复，可能导致歧义，建议使用$\tau$代替***时序***下标$t$

**Comment by LooperXX** [comment]
解释：这里的两类条件概率的参数是根据时序下标$t$相应从对的参数矩阵中取出的，并不是定值，需要依赖$t$

**Comment by lintongmao** [comment]
> 解释：这里的两类条件概率的参数是根据时序下标$t$相应从对的参数矩阵中取出的，并不是定值，需要依赖$t$

你对***这里***的参数的理解可能有点问题，为了不失一般性，请不要把模型和算法混淆。

**Comment by LooperXX** [comment]
> > 解释：这里的两类条件概率的参数是根据时序下标$t$相应从对的参数矩阵中取出的，并不是定值，需要依赖$t$
> 
> 你对_**这里**_的参数的理解可能有点问题，为了不失一般性，请不要把模型和算法混淆。

我认为这里确实如你所说，公式中想要表述的参数指的是状态转移矩阵和混淆矩阵，应当采用时序下标$t$不同的下标加以区别，我上一解释超出了这一公式的表述目的
