### ISSUE TITLE
建议 P273 11.3.1蒙特卡洛方法

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#342]
# 建议 P273 11.3.1蒙特卡洛方法

- [ ] 蒙特卡洛方法一节中，在**随机采样**后面给出了**逆采样**的思路，但是没有引入**逆采样**这个术语，是否考虑在这一部分添加“...这就是逆采样（Inverse Sampling）的思路”，或者单独给这个方法开一个小节？

**Comment by LooperXX** [comment]
- [ ] 建议：添加**逆采样**`Inverse Sampling`作为和**拒绝采样**与**重要性采样**同样重要的单独一小节

**Comment by GH1995** [comment]
建议增加相关图片，助于理解

![](https://upload.wikimedia.org/wikipedia/commons/6/68/Inverse_transform_sampling.png?1558871733545)
