### ISSUE TITLE
公式一致性问题  11.4.1 公式11.77

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#344]
# 公式一致性问题  11.4.1 公式11.77

- [ ] 在***不含隐变量的参数估计***一小节中，无向图的对数似然函数公式11.77中的概率$p(\mathbf{x}^{(i)}, \theta)$使用了联合概率的形式，而公式11.76中使用的是条件概率形式$p(\mathbf{x}| \theta)$，我认为应该予以统一，方便前后对照。如我的理解有问题烦请指正。
- [ ] 同样的疑问还出现在公式11.73、公式11.85，均使用了联合概率形式。

**Comment by LooperXX** [comment]
不知为何两处分别使用了条件概率和联合概率，如有理解的同学，烦请指出。

**Comment by lintongmao** [comment]
是否可以考虑将参数使用分号隔开，这似乎是比较常见的写法：$p(\mathbf{x}^{(i)}; \theta)$

**Comment by xpqiu** [comment]
谢谢，我会修改。之前就有这样的打算，但工作量比较大。

**Comment by xpqiu** [comment]
我会逐步修改。
