### ISSUE TITLE
对Jenson不等式描述错误 P283 公式11.89下方

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#346]
# 对Jenson不等式描述错误 P283 公式11.89下方

- [ ] “公式 (11.88) 使用了 Jensen 不等式(即对于***凹*** 函数...”，这里错把***凸函数*** 写成了凹函数。

**Comment by LooperXX** [comment]
Jensen不等式对于凹函数g，有g(E[X])≥E[g(X)]；对于凸函数g，有g(E[X])≤E[g(X)]。

**Comment by lintongmao** [comment]
谢谢，符号看错了
