### ISSUE TITLE
公式12.23-12.27存疑 P297玻尔兹曼机

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#357]
# 公式12.23-12.27存疑 P297玻尔兹曼机

- [ ] 公式12.3中，对$\exp(-E(\hat{\mathbf{v}}^{(n)}, \mathbf{h}))$的求导疑似缺少负号？
<img width="400" alt="屏幕快照 2019-05-29 11 03 19" src="https://user-images.githubusercontent.com/33687938/58526507-be40b280-8201-11e9-931d-1f8b7039778c.png">

如果我的求导无误，那么公式12.23-12.27、公式12.53-12.55中的左右两项应该反过来。

**Comment by xpqiu** [comment]
谢谢，这里是少了个负号。已修正。12.26-12.27、公式12.53-12.55不需要反过来。
