### ISSUE TITLE
自信息部分的建议 P427

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#366]
# 自信息部分的建议 P427

- [ ] 在P427上方的表格给出了一个不同分布的熵的小例子，其中第二行的熵为3/2，根据前面的注释“在熵的定义中，对数的底可以使用 2、自然常数 e，或是 10。”，在这里为了不失一般性，建议：
    - 添加“使用2作为对数的底”的假设；
    - 或者，将第二行的熵改为$\frac{3}{2} \log{2}$

- [ ] 另外，该表格第三行的熵中$\log$后的括号是否多余
- [ ] 建议在E.1.1的第一段中引入自信息的英文术语Self Information。

**Comment by xpqiu** [comment]
谢谢，已修正。
