### ISSUE TITLE
错别字 P429 信息论JS散度

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#367]
# 错别字 P429 信息论JS散度

- [ ] 最上方第一行“但两种散度**有**存在一个问题”，应该改成“但两种散度**都**存在一个问题”
- [ ] 同一段中，“如果两个分布 p, q **个分布**没有重叠或者重叠非常少时”，应该删除第二个“个分布”
- [ ] E.3.4第一段，“Wasserstein 距离(Wasserstein Distance)也**是**用于衡量两个分布之间的距离”，疑似这里的“是”是多余的。

**Comment by xpqiu** [comment]
谢谢，已修正。
