### ISSUE TITLE
错别字+190页

### ISSUE THREAD

**Issue by changhuiMichael** [nndl/nndl.github.io#369]
# 错别字 + 190页倒数14行+伯努利分布写成贝努力分布（可能是翻译的问题）
### **

1. 错别字（190页倒数14行）-伯努利分布写成贝努力分布。（可能是翻译的问题）

**
- [ ] 错别字：P66 公式2.3 下面一行“1111”改为“2222”  （参考示例1）
- [ ] 推导错误：P66 公式2.3 中推导错误，。。。 （参考示例2）

**Comment by lintongmao** [comment]
这只是音译的不同

**Comment by xpqiu** [comment]
谢谢，已修正。
