### ISSUE TITLE
chap-卷积神经网络Lenet5卷积层滤波器个数

### ISSUE THREAD

**Issue by shenlanyilang** [nndl/nndl.github.io#37]
卷积神经网络章节，LeNet-5的介绍中，第4条C3层使用60个5X5滤波器，得到16组大小为10X10的特征映射。上一层汇聚层神经元个数为6X14X14个，这一层不应该是6X16=96个5X5的滤波器才能得到16组大小为10X10的特征映射吗？

**Comment by xpqiu** [comment]
参考图5.11连接表的设定。
