### ISSUE TITLE
上下文不一致 P191 丢弃法

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#370]
# 上下文不一致 P191 丢弃法

- [ ] 公式7.65下方，“在测试时需要将每一个神经元的**输出**乘以 p”，根据公式7.65，应该是**输入**更妥当；
- [ ] 公式7.65下方丢弃掩码“$\mathbf{m}\in \{ 0, 1 \}^d$”，提到了维度d，建议在前文添加前提$\mathbf{x}\in\mathbb{R}^d$

**Comment by xpqiu** [comment]
谢谢，已修正。
