### ISSUE TITLE
疑似描述有问题 P334

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#373]
# 疑似描述有问题 P334

- [ ] 在公式13.56上方，“为了使得$f(\mathbf{x};\phi)$满足 K-Lipschitz 连续，可以令导数$\| \frac{\partial f(\mathbf{x};\phi)}{\partial \mathbf{x}}\|$有界。”，如果意思是 **导数** 有界，那么是否应该去掉范数符号？或者使用范数小于等于某个量来表示？

**Comment by xpqiu** [comment]
谢谢，已修正。
