### ISSUE TITLE
符号一致问题 P368-369

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#382]
# 符号一致问题 P368-369

- [ ] 这两页中用来表示神经网络的函数符号中，参数前的符号一直在**分号**和**逗号**间变化。如在公式15.21中，使用了逗号形式：f(x, \theta)，类似的情况还出现在公式15.26-15.28、公式15.26下方的$g(\cdot, \theta_g)$。建议将这些地方的逗号改为分号。

**Comment by xpqiu** [comment]
谢谢，已修正。
