### ISSUE TITLE
层次化Softmax的建议 P376

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#385]
# 层次化Softmax的建议 P376

- [ ] 该页最后一段，“一般对于词表大小|V|，我们将词平均分到√|V|个分组中，每组 √|V|个词。”，请考虑是否需要假设词表大小|V|是k^2的形式，即假设√|V|是整数。

**Comment by xpqiu** [comment]
谢谢，这里不用特殊说明。
