### ISSUE TITLE
Huffman树构建算法描述问题 P378 算法15.1

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#386]
# Huffman树构建算法描述问题 P378 算法15.1

- [ ] 算法第四行"从集合S选择两 ***棵*** 概率最低的 ***节点***  n1 和 n2 ;"，考虑到单个节点和构建的二叉树都可以描述为二叉树，这里的“节点”改成“二叉树”是否更加妥当？如果更改为“二叉树”，请考虑将下面的“子节点”一并修改为“子树”。

**Comment by xpqiu** [comment]
谢谢，已修正。
