### ISSUE TITLE
15.5.3.2 重要性采样若干问题 P379-281

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#387]
# 15.5.3.2 重要性采样若干问题 P379-281

- [x] 公式15.67上方，“根据分布Q(v|ht)独立采样K个样本”，这里的Q是否应该是小写？
- [x] 公式15.68上方，“依然需要每一个 **计算** 抽取样本的概率”，“计算”是否应该移到“每一个”前面？
- [x] P381第二段中，“建议分布”建议改成“提议分布”，和前面的术语保持一致。

**Comment by xpqiu** [comment]
谢谢，已修正。
