### ISSUE TITLE
符号错误 P382

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#388]
# 符号错误 P382

- [x] 公式15.87上方，“然后从噪声分布中抽取KN 个样本$x'_1, \cdots, x'_{kn}$”，这里最后一个x'的下标应该是大写的KN。
- [x] 公式15.88下方，“从噪声分布中抽取 K个样本$(x'_{t,1}, \cdots, x'_{t,k})$”，这里的最后一个下标中的k应该是大写K，另外，改成“从噪声分布中抽取 KT个样本$\{(x'_{t,1}, \cdots, x'_{t,K})\}_{t=1}^T$”会不会更好一些

**Comment by xpqiu** [comment]
谢谢，已修正。
