### ISSUE TITLE
15.6 序列到序列模型 勘误

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#389]
# 15.6 序列到序列模型 勘误

- [x] P384第一段，"比如在机器翻译中，输入源语言，**输入**为目标语言。"，第二个"输入"应该改为"输出"。
- [x] P385公式15.103下方，"基于循环神经网络的序列到序列模型的缺点是:(1)向量 $\mathbf{c}$的容量问题"，这里是否应该改成向量$\mathbf{u}$。
- [x] P386 15.6.3.2 多头自注意力， "自注意力模型可以看作是在一个线性投影空间中建立**向量 H** 之间交互关系。"，我觉得应该改成"建立**H中的向量**之间的交互关系"。
- [x] 公式15.111下方，$m\in[1,M]$，这里似乎不适用连续区间。
- [x] 公式15.113、15.114及上方的描述中，隐状态H和Z的书写各有一处使用了粗体，不一致。

**Comment by xpqiu** [comment]
谢谢，已修正。
