### ISSUE TITLE
符号错误 P366 公式15.11上方

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#390]
# 符号错误 P366 公式15.11上方

- [x] “给定一组训练集$\{\mathbf{x}^{(n)1:T_n}\}_{n=1}^{N'}$”，这里的上标中的$1:T_n$，应该作为下标，即$\{\mathbf{x}^{(n)}_{1:T_n}\}_{n=1}^{N'}$。
- [x] 公式15.18中的下标k，有两个用途，建议将分母中的k改成i；另外上面描述文字中的$\sum_{v=1}^{V}$应该改成$\sum_{v=1}^{|\mathcal{V}|}$

**Comment by xpqiu** [comment]
谢谢，已修正。
