### ISSUE TITLE
附录部分的若干问题和建议

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#391]
# 附录部分的若干问题和建议

- [x] P395公式A.20上方 "假设有两个A和B分别表示两个线性映射"，最好改成 "假设有两个 **矩阵** A和B分别表示两个线性映射"
- [x] P396公式A.26 缺少符号$\mathrm{sgn}$
- [x] P398A.2.4的标题中"特征矢量"最好改成"特征向量"，与下文保持一致
- [x] P402 B.1.2.3链式法则中，是否需要添加"假如偏导数使用分母布局表示"？因为在分子布局中，链式法则的顺序应该反过来。
- [x] P406 C.1.1.1 "整数规划(Integer Programming):输入变量$\mathbf{x}\in\mathbb{Z}^d$为整数"应该删掉"为整数"，输入是一个向量，其中的元素是整数。
- [x] P406 C.1.1.1 "但是这种方法得到的解一般都不是最优的，因此原问题的最优解不一定在松弛问题最优解的附近。"，这里的"因此"前后是否需要对调？或者将"因此"改成"因为"？
- [x] P407 C.1.3 线性优化和非线性优化 "并且等式约束函数为线性函数，不等式约束函数为**凹函数**"，不等式约束函数应该是凸函数，参考http://cs229.stanford.edu/section/cs229-cvxopt.pdf
- [x] P413 D.2 "概率(Probability)表示一个随机事件发生的可能性大小，为 0 到 1 之间的一个***非负***实数。"，这里的"非负"似乎冗余。
- [x] 公式D.6 $\forall i\in[1,n]$，这里i是离散的情况，不适合用区间表示。
- [x] 二项分布 公式D.8上方，"在n次伯努利**分布**中"改成"在n次伯努利**试验**中"似乎更合理。

**Comment by xpqiu** [comment]
谢谢，已修正。
