### ISSUE TITLE
https://nndl.github.io/ 首页上序列生成模型 [ppt] 下载链接404

### ISSUE THREAD

**Issue by cychenyin** [nndl/nndl.github.io#392]
序列生成模型 [ppt] 下载链接 https://nndl.github.io/ppt/chap-%E5%BA%8F%E5%88%97%E7%94%9F%E6%88%90%E6%A8%A1%E5%9E%8B.pptx 返回404

**Comment by yzfxmu** [comment]
> 序列生成模型 [ppt] 下载链接 https://nndl.github.io/ppt/chap-%E5%BA%8F%E5%88%97%E7%94%9F%E6%88%90%E6%A8%A1%E5%9E%8B.pptx 返回404

同错误，另外请问第10和16没有PPT吗
谢谢
