### ISSUE TITLE
第7章中的公式 7.5是不是少了对f的导数？

### ISSUE THREAD

**Issue by hkxIron** [nndl/nndl.github.io#4]
第7章中的公式 7.5是不是少了对f的导数？另外，公式中直接将U写出，也未介绍u的含义与数学的定义。

**Comment by xpqiu** [comment]
感谢指出错误！如果方便的话可否告诉我你的名字，我在书中正式致谢：）

**Comment by hkxIron** [comment]
你好，我叫胡可鑫，毕业于四川大学。非常高兴看到关于深度神经网络方面的中文书籍，不知可否加入最近比较火的 gan的篇章。谢谢
----- 原始邮件 -----
发件人：Xipeng Qiu <notifications@github.com>
收件人："nndl/nndl.github.io" <nndl.github.io@noreply.github.com>
抄送人：hkxIron <hkxfuture@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[nndl/nndl.github.io]_第7章中的公式_7.5是不是少了对f的导数？_(#4)
日期：2016年12月05日 09点04分

感谢指出错误！如果方便的话可否告诉我你的名字，我在书中正式致谢：）

&mdash;

**Comment by xpqiu** [comment]
GAN的内容已在写：）
