### ISSUE TITLE
表述错误 P93页

### ISSUE THREAD

**Issue by mhChen-1991** [nndl/nndl.github.io#407]
邱老师好！我是初学者，不知道理解得对不对。
表述错误 P93页  4.1.4 Maxout 单元 第一段中

“而 maxout 单元的输入是上一层神经元的全部原始输入”
我理解应该改为
“而 maxout 单元的输入是上一层神经元的全部原始输出”
即：“输入”改为“输出”

或改为
“而 maxout 单元的输入是神经元本身的全部原始输入”

**Comment by xpqiu** [comment]
多谢，已修正。
