### ISSUE TITLE
多余的字  P100页  公式4.50下方

### ISSUE THREAD

**Issue by mhChen-1991** [nndl/nndl.github.io#412]
多余的字  P100页  公式4.50下方第一段
原文：
“公式 (4.49) 和 (4.50) 中的第二项是都为目标函数关于第 l 层的神经元 z (l) 的偏导数，称为误差项”

其中“是都为”改为“都为”，  “是”字多余

**Comment by xpqiu** [comment]
已修正，谢谢。
