### ISSUE TITLE
# 疑似打错字，“梯度方法”，应为“梯度方向” +，p171

### ISSUE THREAD

**Issue by gaoweichun** [nndl/nndl.github.io#416]
# 疑似打错字，“梯度方法”，应为“梯度方向” +，p171

- 7.2.3.1动量法小节最后一段

> 在迭代初期，梯度方法都比较一致，动量法会起到 加速作用，可以更快地到达最优点。在迭代后期，梯度方法会取决不一致

中的迭代方法，是不是应为迭代方向。

**Comment by mhChen-1991** [comment]
你看的是旧版吧。我在2019-7-23版本看到，都是正确的了，建议可以关闭了

**Comment by gaoweichun** [comment]
> 你看的是旧版吧。我在2019-7-23版本看到，都是正确的了，建议可以关闭了
我该更新了。
