### ISSUE TITLE
4.4 反向传播算法 公式（4.51）求导的疑问

### ISSUE THREAD

**Issue by freshfish1986** [nndl/nndl.github.io#417]
公式（4.51）<a href="https://www.codecogs.com/eqnedit.php?latex=z^{l}=W^{l}a^{l-1}&plus;b^{l}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?z^{l}=W^{l}a^{l-1}&plus;b^{l}" title="z^{l}=W^{l}a^{l-1}+b^{l}" /></a>，其中<a href="https://www.codecogs.com/eqnedit.php?latex=z^{l}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?z^{l}" title="z^{l}" /></a>、<a href="https://www.codecogs.com/eqnedit.php?latex=b^{l}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?b^{l}" title="b^{l}" /></a>、<a href="https://www.codecogs.com/eqnedit.php?latex=a^{l-1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?a^{l-1}" title="a^{l-1}" /></a>均为列向量。

<a href="https://www.codecogs.com/eqnedit.php?latex=W^{l}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W^{l}" title="W^{l}" /></a>为n*m为矩阵，<a href="https://www.codecogs.com/eqnedit.php?latex=a^{l-1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?a^{l-1}" title="a^{l-1}" /></a>为m维列向量，<a href="https://www.codecogs.com/eqnedit.php?latex=b^{l}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?b^{l}" title="b^{l}" /></a>为n维列向量，则<a href="https://www.codecogs.com/eqnedit.php?latex=z^{l}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?z^{l}" title="z^{l}" /></a>为n维列向量；但是公式(4.51)计算导数的时候却把<a href="https://www.codecogs.com/eqnedit.php?latex=z^{l}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?z^{l}" title="z^{l}" /></a>表示成行向量，与<a href="https://www.codecogs.com/eqnedit.php?latex=z^{l}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?z^{l}" title="z^{l}" /></a>为列向量不符，我觉得2019年4月6日发布的版本的推导是正确的。

**Comment by xpqiu** [comment]
这里的矩阵微分采用分母布局，即一个列行向量关于标量的偏导数为行向量，参见第B.1.1节。
我会在下次更新时加上说明，避免歧义。
