### ISSUE TITLE
缺少图中符号说明  P146 图6.5

### ISSUE THREAD

**Issue by mhChen-1991** [nndl/nndl.github.io#419]
P146 图 6.5 异步的序列到序列模式
图里有一个符号“\<eos\>”，但是在上下文中没有相关说明，出现得很突然。
经搜索，才知道
“\<eos\>”来表示序列的结束
在15.1 序列概率模型  才有介绍。

建议在图 6.5边上增加“\<eos\>”符号的简单相关说明

**Comment by xpqiu** [comment]
已修正，谢谢。
