### ISSUE TITLE
Perceptron在书中几处翻译不一致

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#432]
# Perceptron在书中几处翻译不一致

- [ ] Perceptron在书中大部分内容中被翻译为“感知器”，但是在几处仍然使用“感知机”，不知是否需要修改：
- P12：冰河期部分 - “1969年，Marvin Minsky出版《感知**机**》一书”【注：这本书在后续章节中被译为《感知器》】
- 同一段落中，“第一个是感知**机**无法处理异或回路问题;” 
- P78：最后一个自然段：“Rosenblatt [1958]最早提出了两类感知器算法，并随后给出了感知**机**收敛定理。”

**Comment by xpqiu** [comment]
已修正。
