### ISSUE TITLE
对于局部表示只提了缺点，没有提到优点。P.16开头部分

### ISSUE THREAD

**Issue by zn19920623** [nndl/nndl.github.io#434]
文中对于局部表示只提到了缺点，没有提到优点。
从工程化的角度看局部表示one-hot，将所有类型的特征做one-hot，在线上做inference的时候速度会非常快(比如线上用FTRL，w*x中的x只能取1或者0，等于是个加法运算)，特征工程处理也会非常方便，直接做cross就可以表达非线性。另外在追溯badcase的时候也会非常方便。这些都是相对于DNN的优点。
个人愚见很多厂在过渡到DNN之前都会用这种方式做inference，甚至还有不少团队依然在用类似的方式做线上inference服务。
非常希望文章能把局部表示的优点加上去。

**Comment by xpqiu** [comment]
谢谢建议，我在下次更新加上去。

**Comment by xpqiu** [comment]
已修正，谢谢。
