### ISSUE TITLE
表达有误 + p183 (标准归一化)

### ISSUE THREAD

**Issue by allenwind** [nndl/nndl.github.io#436]
p183 标准归一化部分：

“将每一个维特征都处理为符合标准正态分布(均值为 0,标准差为 1)” 
"在标准归一化之后,每一维特征都服从标准正态分布。"   

表达有误。

标准归一化，并不能改变原始数据所属的分布簇。例如，如果数据本身是均匀分布，经过标准归一化后数据还是均匀分布。

把原始数据变换为 Gaussian-like 分布，通常使用 yeo-johnson 或 box-cox 方法。

**Comment by xpqiu** [comment]
谢谢，已修正。
