### ISSUE TITLE
符号问题 P97

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#443]
# 符号问题 P97

- [ ] P97上方段落中的两个phi长得不一样，不知道是什么原因？

<img width="553" alt="屏幕快照 2019-08-28 23 51 06" src="https://user-images.githubusercontent.com/33687938/63871631-cff74900-c9ee-11e9-83bb-ede69aeb5b48.png">

**Comment by xpqiu** [comment]
谢谢，已修正。
