### ISSUE TITLE
# 我们只能活大约10^9 秒 P223

### ISSUE THREAD

**Issue by zenglian** [nndl/nndl.github.io#447]
> 大脑有大约10^14 个突触，我们只能活大约10^9 秒。所以我们
有比数据更多的参数。这启发了我们必须进行大量无监督学习
的想法，因为感知输入（包括本体感受）是我们可以获得每秒105
维约束的唯一途径。
— Geoffrey Hinton, 2014 AMA on Reddit

10^9 秒大约等于32年。我们只能活大约32年？好像不对吧😄

**Comment by EncodeTS** [comment]
这里说的应该是数量级，再多一个0或者少一个0数量级都不对了，不过的确可以想下怎么换一个更好的表述

**Comment by lintongmao** [comment]
这里应该是指数量级了，这段话确实是原文，LeCun 2017年在清华的演讲上面给出来的：
> “The brain has about 10^14 synapses and we only live for about 10^9 seconds, So we have a lot more parameters than data. This motivates the idea that we must do a lot of unsupervised learning since the perceptual input (including proprioception) is the only place we can get 10^5 dimensions of constraint per second.”

**Comment by xpqiu** [comment]
已注明。
