### ISSUE TITLE
修改建议_2017年11月28日版本

### ISSUE THREAD

**Issue by 4Statistics** [nndl/nndl.github.io#45]
1.第93页_第5章_正文第三段。“参数的规模也会极具增加”，应该是“急剧增加”。
2.第95页，倒数第7行，“图5.4给出了一维卷积示例”。我看了上下文，估计作者指的应该是“图5.1”吧.
3.第102页，图5.6中，图形左半部分标注为“高度M、宽度N”,但是下面的正文写的是“高度N、宽度M”。是       否需要保持一致？

                                                         --读者：刘永辉
感谢作者的无私共享。

**Comment by xpqiu** [comment]
已修正，多谢！
