### ISSUE TITLE
P134 边注与页脚重叠

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#453]
# P134 边注与页脚重叠

- [ ] P134，空洞卷积的动图二维码，与页脚重合：

<img width="246" alt="image" src="https://user-images.githubusercontent.com/33687938/65298882-c1d8ba80-db9f-11e9-8e63-02aa3282f189.png">

**Comment by lintongmao** [comment]
还有该页的另一个边注位置也有问题：‘Atrous一词来源于法语à trous，意为“空洞，多孔”。’，建议把这个注解放到前一页。

**Comment by xpqiu** [comment]
已修正。
