### ISSUE TITLE
感觉公式有点问题，最新版电子书352页 公式（15.107）

### ISSUE THREAD

**Issue by Shijie97** [nndl/nndl.github.io#458]
这个公式的V是不是应该写在括号的外面？

**Comment by xpqiu** [comment]
谢谢，已修正。

**Comment by Shijie97** [comment]
邱老师辛苦了！




| |
周世杰
|
|
邮箱：sjzhou97@126.com
|

签名由 网易邮箱大师 定制

在2019年10月25日 01:33，Xipeng Qiu 写道：

Closed #458.
