### ISSUE TITLE
关于图5.2中卷积的计算方式有疑问_20171128版本

### ISSUE THREAD

**Issue by 4Statistics** [nndl/nndl.github.io#46]
关于图5.2的计算方式_20171128版本

	96页，第5章，图5.2，二维卷积示例。
示例中的计算，左上角的1，为什么是和卷积核中右下角的“-1”相乘？
	是不是应该乘以卷积核中左上角的1？---和其他地方看到的卷积计算方法不一样。
        还是因为做了其他的处理呢？--是不是因为做了翻转？如果是这样，好像计算方法是合理的。
        谢谢.

--读者：刘永辉
感谢作者的无私共享。

**Comment by xpqiu** [comment]
因为卷积的原始定义是这样的。
