### ISSUE TITLE
请问 该书会出纸质版嘛

### ISSUE THREAD

**Issue by atarik91** [nndl/nndl.github.io#461]
请问 该书会出纸质版嘛

**Comment by lilong666** [comment]
我也想问一下，该书有没有配套的视频？

**Comment by DaSEPeng** [comment]
> 我也想问一下，该书有没有配套的视频？

你好，我之前整理了一份资料，视频主要是台大李宏毅老师的机器学习和深度学习课程（可以在B站找到对应视频），以及B站的“白板推导系列”，几乎涵盖邱老师这本书的所有内容，如果需要可以参考：[Machine Learning](https://dasepeng.github.io/Machine-Learning/)

ps：网页的课后习题与编程练习两列容我慢慢更（考研狗...）

**Comment by xpqiu** [comment]
会出版的。但是之前还要修改几遍：）
