### ISSUE TITLE
typo P225 公式9.12上方

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#465]
# typo P225 公式9.12上方

- [ ] $l_0$范数被误写成了范式。

**Comment by lintongmao** [comment]
- [ ] 另外，公式9.11中的目标函数字体和别处不一致，是不是应该用$\mathcal{L}(A,Z)$；这里的$Z$虽然可以知道是所有x的编码，但是在前文好像没有引入过...

**Comment by xpqiu** [comment]
多谢，已修正。
