### ISSUE TITLE
稀疏自编码器部分 公式9.25和9.28的一点疑问

### ISSUE THREAD

**Issue by lintongmao** [nndl/nndl.github.io#466]
# 稀疏自编码器部分 公式9.25和9.28的一点疑问

- [ ] 在公式9.25和9.28中，第二项稀疏性度量被写作$\rho(\mathbf{z}^{(n)})$ ，但是，如果考虑公式9.26，不难发现，这里的KL散度应该不只是关于$\mathbf{z}^{(n)}$的函数，而是与所有的$\\{\mathbf{z}^{(i)},i=1,\cdots,N\\}$都有关。所以公式9.25和9.28似乎是有一点不妥？感觉写成关于网络参数的函数好像要更合理一点...

**Comment by xpqiu** [comment]
谢谢，已修正。
