### ISSUE TITLE
附录部分的两处 typo

### ISSUE THREAD

**Issue by LooperXX** [nndl/nndl.github.io#467]
# typo + P398 & 415

- [ ] 错别字：P398 公式A.10 上方 “笛卡儿坐标” 改为 “笛卡尔坐标”
- [ ] 公式错误：P415 C.2 第一段第二行 "$\boldsymbol X_2$" 改为 “$\boldsymbol x_2$”

**Comment by xpqiu** [comment]
多谢，已修正。
