### ISSUE TITLE
描述错误:P424

### ISSUE THREAD

**Issue by davidwang9527** [nndl/nndl.github.io#471]
#描述错误P424

"给定概率密度函数p(x)，便可以计算出随机变量落入某一个区间的概率，而p(x)本身反映了随机变量取落入x的非常小的邻近区间中的概率大小。"这句话是不准确的，因为p(x)本身是可以大于1的，所以不能说p(x)反映了概率大小，可以说p(x)与x的非常小的临近区间的乘积反映了随机变量在这个区间内的概率大小。

**Comment by xpqiu** [comment]
多谢，已修正。
