### ISSUE TITLE
p282的信念传播算法的计算复杂度O(TK^3) vs O(TK^2)？？？

### ISSUE THREAD

**Issue by XiaojunTan** [nndl/nndl.github.io#476]
# 最新版本中信念传播算法的计算复杂度是不是搞错了or typo + p283公式(11.80)后面。

公式(11.37)中的O(TK^2)个人认为应该是改为O(TK^3)，非常类似于T个大小为K\times K 的方阵的乘积的复杂度。

**Comment by xpqiu** [comment]
是类似，但两端是向量。从两端往中间乘，复杂度就是O(TK^2)
