### ISSUE TITLE
错别字+ p143(6.33)

### ISSUE THREAD

**Issue by mouthful** [nndl/nndl.github.io#480]
# 错别字+ p143(6.33)
我对公式（6.33）的等价结果有点疑问，结果本身已经是一个行向量，怎么会有![CodeCogsEqn](https://user-images.githubusercontent.com/33189249/68729555-4a566300-0605-11ea-9158-685c660ea977.gif) 这个说法存在呢，不应该是![CodeCogsEqn (1)](https://user-images.githubusercontent.com/33189249/68729744-be910680-0605-11ea-84d8-acd5401cb6f0.gif)来描述行向量的第 **j** 个元素不为0吗？

- [1] 错别字：P66 公式6.33 最后一个变量的下标由 **i** 改为 **j**

**Comment by xpqiu** [comment]
这里没有问题，i和j不一样。
