### ISSUE TITLE
关于本书命名与组织结构的另一种思考

### ISSUE THREAD

**Issue by DaSEPeng** [nndl/nndl.github.io#481]
老师，自己本来想系统读完本书并完全消化后再提出这个问题的，但是一是考虑到这本书这个月月底就计划要出版，二是考虑到自己近期备考考研时间紧张，可能无法在月底彻底读完本书了，所以就只能把自己一直思考的一个问题提前issue出来，合理与否，还请老师指教：

在学生目前的知识体系中，学生认为整个“机器学习”主要包括由**频率学派**发展而来的“**统计机器学习模型**”和由**贝叶斯学派**发展而来的“**概率图模型**”。而在“统计机器学习模型”与“概率图模型”中，又分别包含浅层模型与深度模型。如“统计机器学习模型”包含浅层的SVM模型，也包含深层的DNN模型；在“概率图模型”中包含浅层的HMM模型，也包含深层的深度信念网络模型。虽然深度学习主要是从统计机器学习中的DNN发展而来的，但是目前可以说统计机器学习和概率图中的深度模型都属于深度学习模型。

因此学生认为本书的书名“神经网络与深度学习”并不是一个非常全面与合理的并列关系，而本书中1.6节图1.6组织结构一图学生认为不如把“概率图模型”与“神经网络”直接包含在“机器学习”里，只考虑“机器学习“中的”概率图模型“和”（人工）神经网络模型“，这样或许更能突出两块重点。

学生整理了一张知识体系框图，是对老师这本书内容的另一种组织，目前还不能保证非常严谨（一些点只是突出了主要的关系），但是由于时间问题，只能提前请老师检查一下了：[知识框图](https://dasepeng.github.io/Machine-Learning/UnifiedFrame.png)（图可放大），学生认为这种体系或许能够把整个机器学习与深度学习的内容组织得更清晰一些。当然，这也只是自己的一种组织思路，还有很多分类方式，正确与否还请老师指教。

另外，学生认为一些章节中的个别名词翻译并不是特别严谨，如”step decay“本书翻译的是”步衰减“，但是学生认为翻译成”阶梯（阶跃）衰减“或许更直观，数学中也有”阶梯函数“这一说法；”reparameterization“的翻译，除了”再参数化“外，目前也多被翻译成”重参数化“；本书中的”两类分类“学生认为统一成”二元分类“或者”二分类“或许更符合大众阅读习惯。另外书的正文与习题中的一些句子的成分搭配（如动宾搭配）并不是完全正确。这些多是一些小问题，但是对于阅读的顺畅性来说确实有一些影响，尤其对于正式的出版物来这个问题可能也比较重要。自己本来想按照章节系统查找一遍的，可惜时间较紧，考研前不一定能完成这项任务了。

学生实知写书不易，非常感谢老师能够系统整理这些内容，学生只是想让这本书更加完美一些，有以上思考供老师参考，学生后期会继续完成本书的学习的。

**Comment by xpqiu** [comment]
谢谢，你先复习考研吧。这本书是一个长期目标，不急着这几个月。即使出版后面也会不断修改的。

**Comment by DaSEPeng** [comment]
> 谢谢，你先复习考研吧。这本书是一个长期目标，不急着这几个月。即使出版后面也会不断修改的。

嗯嗯，一些内容学生考研结束再仔细看，谢谢老师。
