### ISSUE TITLE
最新版12月18日存在内容重叠情况，目前看到的从320开始

### ISSUE THREAD

**Issue by zhengxiang0808** [nndl/nndl.github.io#487]

**Comment by xpqiu** [comment]
谢谢，新版可能已经好了。

**Comment by zhengxiang0808** [comment]
下载了最新，已经好了哈，非常感谢~~








在 2019-12-23 15:50:09，"Xipeng Qiu" <notifications@github.com> 写道：

谢谢，新版可能已经好了。
