### ISSUE TITLE
# 7.3节参数初始化公式错误 + P168 + 公式 (7.35) 和 公式(7.36) 反了

### ISSUE THREAD

**Issue by NY-Chow** [nndl/nndl.github.io#492]
# 7.3节参数初始化公式错误 + P168 + 公式 (7.35) 和 公式(7.36) 反了

- [ ] 推导错误：P168 公式 7.35 和 公式 7.36 反了

1. Logistic 函数在0附近的近似线性函数的导数为 0.25，推导可知公式 7.42的分子为 16，从而公式 7.44 的分子为32，从而公式7.46 的分子为 4 * sqrt(6)。

2. 类似可以推导得出，对于 Tanh 函数, 公式 7.46 的分子为 sqrt(6)。

3. 因此，书中的公式 7.35 和 7.36 正好反了

**Comment by xpqiu** [comment]
多谢，已修正。
