### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by hongtao45** [nndl/nndl.github.io#499]
- [ ] 错别字：P33，“2.3.1参数学习”：
第一行文本中，“给定一组包含N个训练样本的训练集+公式”，公式中的上标“D”改为“N”。

**Comment by hongtao45** [comment]
> * [ ]  错别字：P33，“2.3.1参数学习”：
>   第一行文本中，“给定一组包含N个训练样本的训练集+公式”，公式中的上标“D”改为“N”。

对了，是2020年2月12号更新的最新一版的书中

**Comment by xpqiu** [comment]
谢谢，已修正。
