### ISSUE TITLE
表述错误

### ISSUE THREAD

**Issue by lth787683547** [nndl/nndl.github.io#500]
#142#表述错误，第142页正文第五行首，原文“网络的输入不仅和当前时刻的输入相关”应为“网络的输出不仅和当前时刻的输入相关”

**Comment by lth787683547** [comment]
上面说的142页是pdf的142页，书中的页码是129。
另外，书中132页6.2.1一节最后两行的V的字体（是否黑体）不相同。

**Comment by xpqiu** [comment]
谢谢，已修正。
