### ISSUE TITLE
符号错误(p249)

### ISSUE THREAD

**Issue by ZenMoore** [nndl/nndl.github.io#502]
# 符号错误, p249 公式(10.34) 前的最后一行正文

在转导迁移学习的最后一段内容中，将领域迁移分为两个对抗的目标，第二个方面应该是：“学习参数 \theta_g 使得提取的表示 h 无法被线性判别器 c(h, \theta_c) 预测出来，并同时学习参数 **\theta_f** 使得模型 f(h; \theta_f) 在源领域的损失最小。“，原文中为”并同时学习参数 **\theta_g** 使得模型 f(h; \theta_f) 在源领域的损失最小。“

个人能力有限，可能是自己理解有误，敬请谅解。

**Comment by xpqiu** [comment]
是的，已修正。多谢！
