### ISSUE TITLE
公式符号错误（109页）

### ISSUE THREAD

**Issue by leizhaocs** [nndl/nndl.github.io#504]
在2020-02-11更新的最新版本中，第109页（5.1.2节）的宽卷积公式里，应该是“两端补零 𝑃 = K − 1”，而书中写的是“两端补零 𝑃 = 𝑀 − 1”。

虽然国外有一些类似的神经网络和深度学习的经典书，但是还是觉得中国人写书的风格更严谨，包括章节组织和言简意赅的总结。老外写书太啰嗦。十分感谢邱老师的这本巨著并将其公布到网上。

**Comment by xpqiu** [comment]
谢谢，已修正。请多提建议：）
