### ISSUE TITLE
伪代码错误 算法3.1

### ISSUE THREAD

**Issue by trloveu** [nndl/nndl.github.io#505]
# 算法3.1   两类感知器的参数学习算法

第 10 行 𝑡 ← 𝑡 + 1;   应在for循环外面，即应在11行end后面

**Comment by xpqiu** [comment]
这里T是指样本上迭代次数 iteration，不是epoch。

**Comment by trloveu** [comment]
215版本11行 𝑡 ← 𝑡 + 1; 应在12行end后。您仔细看下。要不然t在for里面，就只能等于N、2N、3N...了。

**Comment by xpqiu** [comment]
嗯，了解了。其实之前就是像你说的这样写的。为了和后面一节的描述一致，就改成这样了。我会在最新版修改下。谢谢
