### ISSUE TITLE
书中7.5.1节中BN层原理的问题

### ISSUE THREAD

**Issue by hy-struggle** [nndl/nndl.github.io#507]
- [ ] 概念有误：P175 原文：为了减少内部协变量偏移问题...
- [ ] 概念有误：P175 原文：虽然归一化操作可以应用在输入 𝒂(𝑙−1) 上，但其分布性质不如𝒛(𝑙) 稳定. 因此，在实践中归一化操作一般应用在仿射变换之后，激活函数之前.

论文[How Does Batch Normalization Help Optimization?](http://cn.arxiv.org/abs/1805.11604)中论证了BN层的效果似乎与对下层输出激活值分布的归一化无关，进而论证了BN层似乎并不会减少内部协变量偏移。

而本文将BN层的效果归结为损失平面的稳定（个人理解为损失函数的导数满足Lipschitzness连续）和光滑（个人理解为损失函数的二阶导满足β-smoothness），类似于ResNet的短链接对损失平面的效果。

综上，“为了减少内部协变量偏移问题”这种说法可能并不准确，且归一化操作应用在仿射变换后和激活函数前效果较好的原因可能并非因为 𝒂(𝑙−1) 的分布性质不如𝒛(𝑙) 稳定.

限于我的个人水平，对您书籍和这篇论文的理解可能并不准确，如有错误请指出。

**Comment by xpqiu** [comment]
多谢反馈这个问题。我已经在新版修改了描述，请你再看下是否合适？

**Comment by hy-struggle** [comment]
看过了，所以您认为这种尺度不变性是否确实有利于网络训练呢？如果据论文中说法，bn的效果是否只是来源于最后一步的缩放和平移变换？

**Comment by hy-struggle** [comment]
> 多谢反馈这个问题。我已经在新版修改了描述，请你再看下是否合适？
看过了，所以您认为这种尺度不变性是否确实有利于网络训练呢？如果据论文中说法，bn的效果是否只是来源于最后一步的缩放和平移变换？

**Comment by hy-struggle** [comment]
> 多谢反馈这个问题。我已经在新版修改了描述，请你再看下是否合适？

看过了，所以您认为这种尺度不变性是否确实有利于网络训练呢？如果据论文中说法，bn的效果是否只是来源于最后一步的缩放和平移变换？

**Comment by xpqiu** [comment]
> > 多谢反馈这个问题。我已经在新版修改了描述，请你再看下是否合适？
> 
> 看过了，所以您认为这种尺度不变性是否确实有利于网络训练呢？如果据论文中说法，bn的效果是否只是来源于最后一步的缩放和平移变换？

是的，归一化本身就可以有利于找到更好的梯度。按论文的Theorem 4.1，他只是证明BN本身，和BN在哪一层插入没有关系。但是好像这一步确实是会和线性变换抵消。

**Comment by hy-struggle** [comment]
> > > 多谢反馈这个问题。我已经在新版修改了描述，请你再看下是否合适？
> > 
> > 
> > 看过了，所以您认为这种尺度不变性是否确实有利于网络训练呢？如果据论文中说法，bn的效果是否只是来源于最后一步的缩放和平移变换？
> 
> 是的，归一化本身就可以有利于找到更好的梯度。按论文的Theorem 4.1，他只是证明BN本身，和BN在哪一层插入没有关系。但是好像这一步确实是会和线性变换抵消。

谢谢！
