### ISSUE TITLE
关于神经网络的层数计算

### ISSUE THREAD

**Issue by ljwh** [nndl/nndl.github.io#51]
邱教授您好！看了您的关于中文分词的很多论文，对我帮助很大，在此感谢！

关于这本书中的对于神经网络的层数记法，我怀有疑问，具体如下：
    在本书中，显然，输入层是计入神经网络的总层数的，但是我看很多论文以及课程中，输入层是不计入神经网络的总层数的。原因是输入层没有可调的参数，不应该被计入神经网络的层数。

如wikipedia.org中对于[Word2vec](https://en.wikipedia.org/wiki/Word2vec)的描述：Word2vec is a group of related models that are used to produce word embeddings. These models are shallow, **two-layer** neural networks that are trained to reconstruct linguistic contexts of words. 

如斯坦福的[cs231n](http://cs231n.github.io/neural-networks-1/)课程中所述：**Naming conventions. Notice that when we say N-layer neural network, we do not count the input layer.** Therefore, a single-layer neural network describes a network with no hidden layers (input directly mapped to output). In that sense, you can sometimes hear people say that logistic regression or SVMs are simply a special case of **single-layer** Neural Networks.

如有错误，还望不吝赐教！

**Comment by xpqiu** [comment]
好的，多谢建议。我会按照这个统一描述。
