### ISSUE TITLE
P151页的 习题 6-2 计算公式 (6.40) 和公式 (6.41) 中的梯度  中”推导“代替”计算“是不是更好，计算容易误导新人

### ISSUE THREAD

**Issue by mrdushe** [nndl/nndl.github.io#510]
# 问题描述（例如：错别字） + 页号或公式号

- [ ] 错别字：P66 公式2.3 下面一行“1111”改为“2222”  （参考示例1）
- [ ] 推导错误：P66 公式2.3 中推导错误，。。。 （参考示例2）

**Comment by xpqiu** [comment]
谢谢，已修正。
