### ISSUE TITLE
关于“第二章，2.3.1.1”伪逆矩阵的描述

### ISSUE THREAD

**Issue by gaoming1977** [nndl/nndl.github.io#512]
# 问题描述（例如：错别字） + 页号或公式号

- [ ] 错别字：P66 公式2.3 下面一行“1111”改为“2222”  （参考示例1）
- [ ] 推导错误：P66 公式2.3 中推导错误，。。。 （参考示例2）

#问题描述：书中伪逆矩阵的定义为“(𝑿𝑿T)−1𝑿”，但好像伪逆矩阵是否应该为“(𝑿T𝑿)−1𝑿T”?其中T, -1为上标。
谢谢，

**Comment by xpqiu** [comment]
嗯，谢谢。应该是𝑿T的伪逆矩阵。已修正。
