### ISSUE TITLE
参考文献附录排版

### ISSUE THREAD

**Issue by Epsilon-Chuan** [nndl/nndl.github.io#520]
# 参考文献附录排版美化

- [ ] 各章的参考文献附录：建议每个占据两行及以上的参考文献条目在排版时，从第二行起每行抬头空出若干字符，方便相邻条目之间的快速区分。当前格式稍显杂乱。

> 可参考周志华《机器学习》一书的参考文献附录排版

**Comment by Epsilon-Chuan** [comment]
各章习题部分的条目也建议可作此更改。

**Comment by xpqiu** [comment]
谢谢，我下一版修正下。

**Comment by xpqiu** [comment]
已修正。

**Comment by Epsilon-Chuan** [comment]
> 已修正。

邱老师奥力给！
