### ISSUE TITLE
无模型的强化学习 

### ISSUE THREAD

**Issue by xa1990615** [nndl/nndl.github.io#525]
P340 无模型的强化学习 
当我们不不知道马尔可夫链的转移函数时候，您在书上说“然后通过随机游走的方法来探索环境” 这个意思是说在 N 个状态的集合中随机选一个状态作为下一个状态么也就是转移概率为 P(S_{t+1} | S_{t}) = 1/N?
我发现在所有的无模型算法里 reward r并不是作为已知的输入。请问每一步 知道 (s_{t-1}, a_{t-1], s_t) 以后，怎么生成 r？

**Comment by xpqiu** [comment]
1. 没有 P(S_{t+1} | S_{t}) = 1/N这个假设，随机游走是指在环境中随机采样得到s_t 到s_{t+1}的样本
2. r也是采样的到得的，然后逆向学习。

**Comment by xa1990615** [comment]
还是没有理解，在没有具体概率分布表达式 P(S_{t+1} | S_{t})和 P(r| s_{t-1}, a_{t-1], s_t) 的前提下怎么进行随机采样? 能写一下具体的采样数学公式么？

**Comment by xpqiu** [comment]
不用知道公式，在环境中采样就行了。

**Comment by xa1990615** [comment]
还是没有理解“在环境中采样”是什么意思？比如状态集合 (s1,s2,...,sn), 上一个状态是 si, 那我该怎么采样下一个状态？还是说这里的“环境”就是默认会随机（条件地）产生一个状态 s_{t+1} | s_{t}) 和回报 r| s_{t-1}, a_{t-1}, s_t, 而我们不必要太关心具体是怎么产生的。

**Comment by xpqiu** [comment]
> 还是没有理解“在环境中采样”是什么意思？比如状态集合 (s1,s2,...,sn), 上一个状态是 si, 那我该怎么采样下一个状态？还是说这里的“环境”就是默认会随机（条件地）产生一个状态 s_{t+1} | s_{t}) 和回报 r| s_{t-1}, a_{t-1}, s_t, 而我们不必要太关心具体是怎么产生的。

是的
