### ISSUE TITLE
公式问题 P316 公式13.28

### ISSUE THREAD

**Issue by LinT-CS** [nndl/nndl.github.io#528]
# 公式问题 P316 公式13.28

- [ ] 公式13.28中，KL散度这一项前面似乎应该是正号？一般看到的其他资料中取-J作为损失函数（最小化）。如果这项需要修改，那么图13.5中也应该相对应地修改

参考：https://arxiv.org/pdf/1907.08956.pdf

**Comment by xpqiu** [comment]
谢谢，是的，这里应该是负号。
