### ISSUE TITLE
神经网络的反向传播算法中的最后一层（即第L层）的误差项怎么计算

### ISSUE THREAD

**Issue by AvailableForTheWorld** [nndl/nndl.github.io#532]
![image](https://user-images.githubusercontent.com/49779788/81523158-93eaf500-937f-11ea-98fb-f4c91280e2d8.png)
第L层的误差项能够通过上述公式求出来吗？
如果求不出来怎么知道第L层的误差项呢？

**Comment by amyrzhang** [comment]
为啥求不出来？损失函数`L`对最后一次激活函数`f`的偏导数 *最后一层激活函数的导数`f^'`（最后一层相当于`M_l`个LR，可以结合LR的梯度下降理解）。

**Comment by AvailableForTheWorld** [comment]
明白了，谢谢您的解答
