### ISSUE TITLE
'通用近似定理' 叙述不准确 (Page93 定理4.1)

### ISSUE THREAD

**Issue by haiwentom** [nndl/nndl.github.io#538]
建议将定理4.1稍作修改，改成：

令 φ(⋅) 是一个.......blabla.......  **对任意给定的一个函数 f ∈ C(I D ) 以及ε>0, 存在一个整数 M , 和一
组实数**.....blabla......
作为函数 f 的近似实现,即
|F(x) − f(x)| < ε, ∀x ∈ I D .(4.38)

**Comment by xpqiu** [comment]
谢谢，已部分更正。
