### ISSUE TITLE
5.5.2节，第一段话，两个3*3卷积比一个5*5卷积参数更少

### ISSUE THREAD

**Issue by llong-debug** [nndl/nndl.github.io#545]
邱老师您好，在5.5.2空洞卷积这一节，第一段话，您列出了增加感受野的三种方式，然后后面说“前两种方式会增加参数数量”，
对于第二种方式，（假如输入数据只有一层）两个3*3*1的卷积核参数3*3*2=18，一个5*5*1卷积核参数5*5=25，应该参数更少了吧。
望老师指正一下我。

**Comment by INC-LUO** [comment]
找错人了？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nndl/nndl.github.io"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 上午10:13
收件人:&nbsp;"nndl/nndl.github.io"<nndl.github.io@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[nndl/nndl.github.io] 5.5.2节，第一段话，两个3*3卷积比一个5*5卷积参数更少 (#545)





 
邱老师您好，在5.5.2空洞卷积这一节，第一段话，您列出了增加感受野的三种方式，然后后面说“前两种方式会增加参数数量”，
 对于第二种方式，（假如输入数据只有一层）两个331的卷积核参数332=18，一个551卷积核参数5*5=25，应该参数更少了吧。
 望老师指正一下我。

**Comment by Swayne32** [comment]
我不是






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nndl/nndl.github.io"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午3:59
收件人:&nbsp;"nndl/nndl.github.io"<nndl.github.io@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [nndl/nndl.github.io] 5.5.2节，第一段话，两个3*3卷积比一个5*5卷积参数更少 (#545)





 找错人了？ 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "nndl/nndl.github.io"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月22日(星期三) 上午10:13 
 收件人:&amp;nbsp;"nndl/nndl.github.io"<nndl.github.io@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[nndl/nndl.github.io] 5.5.2节，第一段话，两个3*3卷积比一个5*5卷积参数更少 (#545) 
 
 
 
 
 
   
 邱老师您好，在5.5.2空洞卷积这一节，第一段话，您列出了增加感受野的三种方式，然后后面说“前两种方式会增加参数数量”， 
  对于第二种方式，（假如输入数据只有一层）两个331的卷积核参数332=18，一个551卷积核参数5*5=25，应该参数更少了吧。 
  望老师指正一下我。
