### ISSUE TITLE
第一次印刷的勘误第2条

### ISSUE THREAD

**Issue by xiaopanchen** [nndl/nndl.github.io#547]
2020年4月第1版第1次印刷
2.	P70 公式3.86上加了一句话“由于同时缩放$w\rightarrow kw$和$b\rightarrow kb$不会改变样本$x^{(n)}$到分割超平面的距离”
应为
2.	**P72** 公式3.86上加了一句话“由于同时缩放$w\rightarrow kw$和$b\rightarrow kb$不会改变样本$x^{(n)}$到分割超平面的距离”

**Comment by xpqiu** [comment]
谢谢，已修改。
