### ISSUE TITLE
电子书7.2.3 学习率调整上方的一段表述

### ISSUE THREAD

**Issue by xiaopanchen** [nndl/nndl.github.io#548]
电子书（p158)7.2.3 学习率调整上方的一段表述
”从图7.3a可以看出，批量大小越大，下降效果越明显，并且下降曲线越平滑．但从图7.3b可以看出，如果按整个数据集上的回合（Epoch）数来看，则是批量样本数越小，适当小的批量大小会导致更快的收敛．“
后半段不太好理解。如果表述成下面的可能更好理解。
”从图7.3a可以看出，批量大小越大，下降效果越明显，并且下降曲线越平滑．但从图7.3b可以看出，如果按整个数据集上的回合（Epoch）数来看，则是批量样本数越小，**下降效果越明显，并且下降曲线越平滑.** 适当小的批量大小会导致更快的收敛．“

**Comment by xpqiu** [comment]
已修正，谢谢！
