### ISSUE TITLE
8.2 注意力机制

### ISSUE THREAD

**Issue by xiaopanchen** [nndl/nndl.github.io#549]
# 问题描述（例如：错别字） + 页号或公式号
1、2020年4月第1版，P199页，公式8.1 上方“选择第i个输入向量”是否应为“”选择第n个输入向量。
同样的问题位于电子书P194
2. 8.2节没有必要设置4级标题吧，只有8.2.1 没有8.2.2，是否可以考了8.2.1下面其他的编号方式？一点拙见

**Comment by xpqiu** [comment]
已修改，谢谢。
第二条建议，我要等第二版更新时，才能调整了。
