### ISSUE TITLE
图 5.2 二维卷积示例

### ISSUE THREAD

**Issue by Moon-xm** [nndl/nndl.github.io#550]
示例计算错误,应该是1

**Comment by xiaopanchen** [comment]
就是图5.2中最左侧一个图中方框框起来的部分，示例是乘以对应的卷积核。实际上经过运算，对照等号右侧的计算结果，应该是卷积核写错了，卷积核的左上角应该是“-1”，右下角应该是“1”

**Comment by DemonsHunter** [comment]
我也觉得这部分计算有问题，我参考的计算方法主要为：https://blog.csdn.net/Herishwater/article/details/90267592。用该方法计算得到的结果是：
[ [0, 1, 0] ,
  [-1, -1, 1],
  [0, 3, 0] ]
希望和大家一起分享

**Comment by DemonsHunter** [comment]
更新一下我评论中的link：
https://blog.csdn.net/Herishwater/article/details/90267592

**Comment by zhangjunroger** [comment]
这是原始卷积计算，没有问题

**Comment by josephcui** [comment]
书上没有问题的，做卷积之前会对矩阵做一个镜像。不同的书在这一块的定义可能不一样。

**Comment by josephcui** [comment]
> 示例计算错误,应该是1

示例没错的，先做了个卷积核翻转。如果是不翻转直接做的话，叫做互相关。具体可以看[吴恩达深度学习P105](https://www.bilibili.com/video/BV1gb411j7Bs?p=105&spm_id_from=pageDriver)这一小节。
