### ISSUE TITLE
英文人名错误 电子版P50 2.8.4节

### ISSUE THREAD

**Issue by sgallon-rin** [nndl/nndl.github.io#551]
# 英文人名错误 P50 2.8.4节

- [ ] 英文人名错误：电子版P50 2.8.4节 丑小鸭定理提出者渡边慧的姓氏拼写 ”Watanable“ 应改为 ”Watanabe“。[(wiki)](https://en.wikipedia.org/wiki/Satosi_Watanabe)

**Comment by xpqiu** [comment]
已修正，谢谢！
