### ISSUE TITLE
错别字 169、170、171页，187页

### ISSUE THREAD

**Issue by shiqi-lu** [nndl/nndl.github.io#556]
# 错别字

- [x] 错别字：P169页 公式7.35 下面一行“均分分布”改为“均匀分布”
- [x] 错别字：P170页 公式7.44 下面一段的第3行“均分分布”改为“均匀分布”
- [ ] 错别字：P171页 公式7.45 下面一段的第3行“均分分布”改为“均匀分布”

- [ ] 错别字：P187页 7.7.5一节中的第4点把“沿水平或垂直方法平移”改为“沿水平或垂直方向平移”

**Comment by shiqi-lu** [comment]
# 错别字 170页

- [ ] 错别字：P170页 公式7.44 下面一段的第3行“均分分布”改为“均匀分布”

**Comment by xpqiu** [comment]
已修正，多谢！
