### ISSUE TITLE
维度理解问题+143页

### ISSUE THREAD

**Issue by zhaoxf4** [nndl/nndl.github.io#557]
# 维度可以调换一下顺序：P143 公式6.59下面一行，W矩阵的维度可以由 4Dx(D+M) 改为 4Dx(M+D)
虽然只是互换了顺序，但更容易理解，按书中公式6.57推导，向量 **x_t** 在向量 **h_t-1** 之前，如果维度一一对应的话，我推导出的结果是**4Dx(M+D)** 。如果有兴趣，您可以检查一下。

**Comment by xpqiu** [comment]
谢谢，已修正。
