### ISSUE TITLE
建议感知机算法部分增加注释帮助理解

### ISSUE THREAD

**Issue by zhaoxf4** [nndl/nndl.github.io#558]
# 增加注释，便于理解，便于区分 + P63算法3.1 + P67算法3.2

- [ ] 我在看感知机算法过程中有些疑问，在网上搜索了一下博客。发现和邱老师所讲内容相近的博客中，repeat...until部分都是用for循环实现的，让我一度认为邱老师的训练轮数错了，后来看了很多遍才理解老师讲的也没有问题。另外博客中的最大迭代次数T指的是最大训练轮数，而邱老师讲的是真正的迭代次数，即训练轮数*样本数量。**希望老师能增加注释，告诉一下读者以上区别。**

- [ ] 可能我个人看for循环的算法比较多，所以会产生这些麻烦问题，老师见谅！参考博客：http://thinkgamer.cn/2019/04/16/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/%E7%BA%BF%E6%80%A7%E6%A8%A1%E5%9E%8B%E4%B9%8BPLA%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F%E6%8E%A8%E5%AF%BC/

**Comment by xpqiu** [comment]
这个博客的算法好像是是从我这本书中以前版本中拷贝的。我为了和后面内容统一，就改成现在这样的。

**Comment by zhaoxf4** [comment]
应该是的，我在下一条里面写了
