### ISSUE TITLE
变量名错误 + P66

### ISSUE THREAD

**Issue by zhaoxf4** [nndl/nndl.github.io#559]
# 变量名错误 + P66 公式3.77下面一行

- [ ] 变量名错误：P66 公式3.77 下面一行“w_{t,n}”改为“w_{t}”  
- [ ] 接上一行，建议说明w_{t}的含义，解释一下t和n的区别

- 原因：个人认为邱老师讲的感知机与[这篇博客](http://thinkgamer.cn/2019/04/16/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/%E7%BA%BF%E6%80%A7%E6%A8%A1%E5%9E%8B%E4%B9%8BPLA%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F%E6%8E%A8%E5%AF%BC/)应该是同根同源的（和算法3.2的参考文献比起来，这篇相似度更高，可能是邱老师之前的版本）。邱老师和这篇博客的区别在于算法3.2中最大迭代次数  T ，邱老师的  T 指的是**最大训练轮数*样本总数**，而博客中的 T 实质上是**最大训练轮数**。那么，博客中的  t  指的是训练某一轮，邱老师的  t  是某一次迭代，即训练过程中某一轮的某一个样本的迭代。所以邱老师的 **w** 中不应该出现 n（某一个样本），实质上已经没有了 n 这个概念，邱老师的 n 个样本，已经扩展为 t 个训练样本了。
- 能力有限，只能讲到这个程度了。但根据我的感觉，在没有辅助的注释情况下，那篇博客更容易理解。

**Comment by xpqiu** [comment]
已修改，谢谢！
这个博客是抄了我的早期版本的描述方式，图片都是我的书里的。
我后面改成目前这种描述方式了：）
