### ISSUE TITLE
第三章支持向量机部分P70页图3.6（支持向量机示例）截距有误

### ISSUE THREAD

**Issue by Hilbert17** [nndl/nndl.github.io#561]
#第三章支持向量机部分P70页图3.6（支持向量机示例）原点到平面的距离有误

距离 “ b / ||w|| ” 应该改为 “b / ||w||^2 ” 
理由如下：
w * x + b = 0，而 w * （k * w + x）= 0，从而得出 k = b / ||w||^2 ，所以图中给出的距离有误。

**Comment by xpqiu** [comment]
![image](https://user-images.githubusercontent.com/6408146/118637063-fafb7f00-b807-11eb-9eb8-41df0097144f.png)
