### ISSUE TITLE
公式错误：P86

### ISSUE THREAD

**Issue by illiterate** [nndl/nndl.github.io#562]
# 公式错误：P86

- [x] 公式错误：P86 公式4.30 上面三行的"𝒙 = [𝑥1 ; 𝑥2 ; ⋯ ; 𝑥𝐷 ]" 改为"𝒙 = [𝑥1 ; 𝑥2 ; ⋯ ; 𝑥𝐷 ]T" （要转置，不转置的话 公式4.30是错误的）

**Comment by Codiola** [comment]
𝒙 = [𝑥1 ; 𝑥2 ; ⋯ ; 𝑥𝐷 ]"就是表示列向量，中间用的是分号，该定义下4.30应该没有问题

**Comment by illiterate** [comment]
> 𝒙 = [𝑥1 ; 𝑥2 ; ⋯ ; 𝑥𝐷 ]"就是表示列向量，中间用的是分号，该定义下4.30应该没有问题

好的，谢谢啦，才知道用分号分隔代表的是列向量
