### ISSUE TITLE
PDF缺失字体，右边栏乱码

### ISSUE THREAD

**Issue by kumiho-gh** [nndl/nndl.github.io#565]
# 问题描述

用Adobe Reader 打开的时候，无法提取嵌入的字体 NEVCXX+FZKTJW--GB1-0 

已经安装了 FZKTJW 字体，是方正简体楷体字体，但是还是展示不了，直接的影响就是右边侧边栏的注释是乱码，但是正文可以正常展示

**Comment by kumiho-gh** [comment]
6月份的pdf有此问题，4月份的pdf无此问题。

**Comment by xpqiu** [comment]
可以能编译问题。
