### ISSUE TITLE
#关于公式的问题 P117 式5.23

### ISSUE THREAD

**Issue by draym28** [nndl/nndl.github.io#567]
在P117中的式5.23，
**z**^l = **W**^p ⊗ **X**^d + b^p
为什么b^p是个标量呢？
**W**^p ⊗ **X**^d的结果是个矩阵
矩阵跟标量怎么相加呢？
难道是矩阵中每个元素都加上b^p的意思吗？

**Comment by xpqiu** [comment]
是的。这个偏置也是所有卷积操作都共享的，所以是个 标量。
