### ISSUE TITLE
“点积”建议改为“Hadamard乘积”  （2020 年 6 月 14 日版本 94页 4.4节 反向传播算法） 

### ISSUE THREAD

**Issue by lll-j** [nndl/nndl.github.io#568]
#公式4.63符号解释有误 + 94页

- 公式(4.63) 的解释：“其中⊙是向量的点积运算符，表示每个元素相乘．”
                建议改为：“其中⊙是向量的Hadamard乘积运算符，表示每个元素相乘．”

**Comment by xpqiu** [comment]
谢谢，已修正。
