### ISSUE TITLE
应该是一个typo?

### ISSUE THREAD

**Issue by ningpingyang** [nndl/nndl.github.io#572]
2020/4第一版，第115页，“5.2 卷积神经网络”，在“局部连接”那一行，

原书文字：在卷积层（假设是第l层）中的每一个神经元都只和下一层（第l-1层）中......，这里的“下一层”应该是“上一层”？

谢谢！

**Comment by xpqiu** [comment]
谢谢，为了避免歧义，修改为“前一层”：）
