### ISSUE TITLE
# IID含义是否应该是Independent and identically distributed 见2.2.2学习准则一节

### ISSUE THREAD

**Issue by Jungle1990** [nndl/nndl.github.io#574]
# IID是否应该是Independent and identically distributed 见2.2.2学习准则一节

- [ ] IID在2.2.2小节解释为 **Identically** and **Independently** Distributed，在Wikipedia上一般解释为 **Independent** and **Identically** Distributed

**Comment by xpqiu** [comment]
谢谢，已修正。
