### ISSUE TITLE
Ch14,P239,P258

### ISSUE THREAD

**Issue by WildeLau** [nndl/nndl.github.io#58]
![image](https://user-images.githubusercontent.com/17998937/34930073-93ce1098-fa02-11e7-8979-397ea1f3c6c3.png)

如上图，公式中没有出现 theta

**Comment by WildeLau** [comment]
![image](https://user-images.githubusercontent.com/17998937/34942341-45d43306-fa32-11e7-9108-73f4b3a572f4.png)

P258，最后一段，是否是“去执行”？

**Comment by xpqiu** [comment]
多谢，已修正。
