### ISSUE TITLE
4.1.1 Sigmoid型函数以及Logistic函数定义有误？

### ISSUE THREAD

**Issue by kingreatwill** [nndl/nndl.github.io#588]
![image](https://user-images.githubusercontent.com/13087689/122895018-50342e80-d37a-11eb-8a45-20cc302e37cc.png)

https://stats.stackexchange.com/questions/204484/what-are-the-differences-between-logistic-function-and-sigmoid-function

我看很多资料说的是Sigmoid函数是Logistic函数的一个特例，当然这里说的是“Sigmoid 型函数”也没有错，但是Logistic函数定义是不是有问题？

**Comment by xpqiu** [comment]
上面的感觉不太对。
https://en.wikipedia.org/wiki/Sigmoid_function
logistic函数的定义，在附录里有。

**Comment by kingreatwill** [comment]
@xpqiu 好的，谢谢！
