### ISSUE TITLE
支持向量机 3.5部分

### ISSUE THREAD

**Issue by ningpingyang** [nndl/nndl.github.io#596]
1. P71，公式（3.82）上面的文字描述，“其中y_n 属于{+1,-1}，建议这里的y_n改成y^(n)，就把索引(n)放到上标，和书本表述统一。
2. P72，在关于支持向量的定义文字描述部分，”如果样本x^(n)在约束边界上，lamda^*_n>=0.这些在约束边界上的样本点称为支持向量“。这里，关于lamda的约束条件应该是：lamda^*_n>0。（是>0，而不是>=0)

**Comment by stvhuang** [comment]
>     1. P71，公式（3.82）上面的文字描述，“其中y_n 属于{+1,-1}，建议这里的y_n改成y^(n)，就把索引(n)放到上标，和书本表述统一。
In the latest version, this is on page 69, right above equation 3.82.

>     2. P72，在关于支持向量的定义文字描述部分，”如果样本x^(n)在约束边界上，lamda^__n>=0.这些在约束边界上的样本点称为支持向量“。这里，关于lamda的约束条件应该是：lamda^__n>0。（是>0，而不是>=0)
In the latest version, this is in second the last paragraph of page 71.

**Comment by ningpingyang** [comment]
OK, thank you! I will close this ticket.

**Comment by stvhuang** [comment]
Hi! @ningpingyang  The problems seem to be not yet solved. Consider reopening this issue.
