### ISSUE TITLE
语句不通顺等

### ISSUE THREAD

**Issue by wujysh** [nndl/nndl.github.io#6]
- [x] 绪论第二段开头：“要`通过`真正地通过图灵测试”
- [x] 2.3.1节“数学小知识 | 笛卡儿乘积”内花色符号缺失`{, , , }`
- [x] 2.3.2节开头：“随机事件（或简称事件）指的是一个被赋`与`机率的事物集合”
- [x] 2.4.1节公式中有大量下标没有处理，“对应的被加数`0 logb 0`的值将会是0”
- [x] 2.4.2节交叉熵的定义为何是英文
- [x] 7.3节第二段开头：“既然增加深度可以`极大`前馈神经网络的能力”

**Comment by xpqiu** [comment]
感谢指出错误！如果方便的话可否告诉我你的名字，我在书中正式致谢：）
