### ISSUE TITLE
课后习题答案

### ISSUE THREAD

**Issue by DoYangTan** [nndl/nndl.github.io#636]
# 课后习题答案在哪里可以找到

- [ ] 老师，我想要课后习题答案（Teacher, how do I ask for the answers to the post-class exercises ）

**Comment by Faith-Uchiha** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您给我发送的邮件已收到。

**Comment by xiaomeng2345** [comment]
您好，我是孟贇祥，您的邮件我已经收到。我会尽快处理麻烦您了。

**Comment by DoYangTan** [comment]
i have found
