### ISSUE TITLE
勘误：第十一章：概率图模型

### ISSUE THREAD

**Issue by hejujie** [nndl/nndl.github.io#69]
首先感谢老师的书籍，非常好的学习材料；下面是在学习概率图模型章节过程中发现的可能是错误的内容。
- P200：最下方；左侧标注与书名重叠；
- P203： 变量消除法上两行。“虽然”后面没有其他文字；
- P204：与P200同样的问题；
- P206：树结构上的信念传播：第一段，少了很多数量词；例如第二行：且只有（）个没有（）结点的结点；第四行：任意两个变量只有（）条路径；
- P206：倒数第五行：从根据结点（根结点？）

**Comment by xpqiu** [comment]
多谢，已修正。
