### ISSUE TITLE
ch4 P57 公式书写

### ISSUE THREAD

**Issue by wandering007** [nndl/nndl.github.io#7]
ch4 57页倒数第二行公式 sign后少了一个左括号。

**Comment by xpqiu** [comment]
多谢，是公式4.15吗？我检查了下，应该没少：）

**Comment by wandering007** [comment]
哦，好的，应该是我看的版本问题。我看到的是这样：
![_20161205114259](https://cloud.githubusercontent.com/assets/6906411/20873191/0b3b59f0-bae0-11e6-9dda-8f5eff4972e0.png)
