### ISSUE TITLE
第一章 绪论修改建议

### ISSUE THREAD

**Issue by suichangyin** [nndl/nndl.github.io#71]
1、第二页倒数第五行：人类大脑是经过了上亿年**的进行**才进行了如此复杂的结构
2、第二页倒数第二行：……发表了一片有**这**重要影响力的论文：“这”修改为“着”
3、第三页第二段最后一句：……看起来就**象**是人所表现出的智能行为一样。：修改为“像”
4、第三页第四段：感知 第二行：人工智能的**研究**主要研究领域包括……：删除“研究”
5、第三页第三段：人工智能的主要领域大体**大体**上可以分为以下几个方面：大体  重复
6、第三页第六段：后者是研究如何让计算机生成**自然**预言：添加**自然**俩字
7、第三页倒数第二行：其发展**上**大体上可以分为：去掉上字
8、第三页右边排版超过篇幅界限错误
9、第四页第二段倒数第三行：一个专家系统必须具备三要素：  无三要素内容
10、第九页第二段：1989年，Yann LeCun**在**将反向传播算法引入了卷积神经网络：删除 在
11、第九页第四段：虽然神经网络可能很容易地增加**增加**层数：增加重复
12、第十页倒数第三段：但是实际操作过程中，因此分类器的性能相差不多，：此处语句不通
13、第十页倒数第一段：我们就需要将输入信息转换为有效**特**的特征：此处特是否多余？
14、第十二页倒数第二段：从**而**避免“特种工程”：添加而字
15、第十三页第四段：因此，**要提高开发一个实际系统**：语句未完
                                     人们往往需要**去**花费大量的精力去尝试设计不通的特征：删除“去”
16、第十三页第五段：可以参考以下材料：1.……2……:未列出参考材料内容
17、第十四页第四段：另外，在人工智能的很**好**应用方向的子领域：很好改为很多
18、第十四页第四段：CVPR和ICCV是计算机视觉方面最好**的**会议：添加“的”

**Comment by xpqiu** [comment]
多谢，已修正。请问下你的名字，我会在书中致谢下。
