### ISSUE TITLE
Page 238  第十四章 深度强化学习page 2

### ISSUE THREAD

**Issue by anxingle** [nndl/nndl.github.io#73]
第十四章深度强化学习 page 2 倒数第八行  
“走到右下角的目标位置E。在每个状态(i, j), 1 ≤ i ≤ 3, 1 ≤ j ≤ 6，格子(2, 1)到” 
应该改为：
走到右下角的目标位置E。在每个状态(i, j), 1 ≤ j ≤ 3, 1 ≤ i ≤ 6，格子(2, 1)到

**Comment by xpqiu** [comment]
多谢，已修正。
