### ISSUE TITLE
循环神经网络中的一公式符号错误

### ISSUE THREAD

**Issue by shanyuwang** [nndl/nndl.github.io#75]
公式（6.7）中，下标i应该改为t。原为：
<img src="http://latex.codecogs.com/gif.latex?\hat&space;y_t&space;=&space;g({\bf&space;h}_t),\forall&space;i&space;\in&space;[1,T]" title="\hat y_t = g({\bf h}_t),\forall i \in [1,T]" />
应改为：
<img src="http://latex.codecogs.com/gif.latex?\hat&space;y_t&space;=&space;g({\bf&space;h}_t),\forall&space;t&space;\in&space;[1,T]" title="\hat y_t = g({\bf h}_t),\forall t \in [1,T]" />

**Comment by shanyuwang** [comment]
公式6.39上方的文字中：

> 梯度消失 梯度消失是循环网络的主要问题。除了使用一些优化技巧外，更有效
> 的方式就是改变模型，比如让U = 1，同时使用f′(zi) = 1。

这里U是矩阵，感觉应该写成U=I

**Comment by xpqiu** [comment]
多谢，已修正。
