### ISSUE TITLE
《12.2 受限玻尔兹曼机》 部分

### ISSUE THREAD

**Issue by KuNyaa** [nndl/nndl.github.io#77]
1) P244 
全连接的玻尔兹曼机虽然只在理论上十分有趣，但是由于其复杂性
->
全连接的玻尔兹曼机虽然在理论上十分有趣，但是由于其复杂性

2) P246  公式(12.45)
w_{i,k}
->
w_{ik}

3) P248
公式(12.53)、(12.54)和(12.55)中都需要计算配分函数Z 以及两个期望E_{p(h|v)}
和 E_{p(h|v)}
->
公式(12.53)、(12.54)和(12.55)中都需要计算配分函数Z 以及两个期望E_{p(h|v)}
和 E_{p(v,h)}

4) P249 公式(12.58)
h_j ← h_j + α(......)
->
b_j ← b_j + α(......)

**Comment by xpqiu** [comment]
已修正，多谢。
