### ISSUE TITLE
第六章-循环神经网络-语句写错了。

### ISSUE THREAD

**Issue by lvjiujin** [nndl/nndl.github.io#79]
第二段
“前馈网络是一个静态网络，明显不能不处理这种情况“   应该修改为前馈网络是一种静态网络，明显不能处理这种情况。多了一个“不” 字。

**Comment by lvjiujin** [comment]
第四段 
在第t个时刻，第l +1层的神经元和下一层神经元的最近q次输出 相关，即h(l+1) t = f(h(l) t ,h(l) t−1,··· ,h(l) t−q+1)。 
根据公式的描述，应该是 第l+1层的神经元和上一次神经元的最近q次输出相关，而不是下一层。

**Comment by xpqiu** [comment]
已修正。
