### ISSUE TITLE
第2章内容修改建议

### ISSUE THREAD

**Issue by Guohai93** [nndl/nndl.github.io#80]
- 2.2.1 模型一节中，假定存在一个未知的“**目标函数**”，既然有优化中的目标函数容易混淆，建议可以修改为“**决策函数**”

- 损失函数一节中关于“0-1损失函数”描述有“但是有个缺点是数学性质不好”，觉得描述过于模糊，可以具体指出其不好的数学性质是不连续不可导缺点

- 2.4.2岭回归一节中，第二行，“即XX^T的秩会解决与0”，语句不通

**Comment by xpqiu** [comment]
谢谢建议，已修正。
