### ISSUE TITLE
13.1.1 密度估计p data 角标是否错了

### ISSUE THREAD

**Issue by solomagix** [nndl/nndl.github.io#83]
![issue](https://user-images.githubusercontent.com/12865942/41917789-ad7f2454-798d-11e8-804b-0a79d5f29b46.jpg)

**Comment by solomagix** [comment]
13.14 公式中有因为排版问题造成的公式重叠
13.1.2pmoel(x)的分布 角标model错误
13.47 公式中有因为排版问题造成的公式重叠

**Comment by xpqiu** [comment]
已修正，谢谢。
