### ISSUE TITLE
ch5 5.4 自动梯度计算 P16

### ISSUE THREAD

**Issue by wandering007** [nndl/nndl.github.io#9]
算法5.1
![image](https://cloud.githubusercontent.com/assets/6906411/21074213/544a90e6-bf2e-11e6-853c-f7e5606c9aba.png)
其中
![image](https://cloud.githubusercontent.com/assets/6906411/21074216/6efd7a52-bf2e-11e6-97c9-2695e77fe609.png)是怎么回事？

**Comment by QipengGuo** [comment]
正则化项的梯度，对应公式(5.36, 5.37)里面的正则化项，通常选取的是二范数，所以就有了这一项
