### ISSUE TITLE
公式错误，第七章 网络优化与正则化 6.2.3.3节 AdaM算法 134页 公式6.22

### ISSUE THREAD

**Issue by kklt007** [nndl/nndl.github.io#95]
公式错误

第六章 网络优化与正则化 6.2.3.3节 AdaM算法 134页 公式6.22

此处参数更新差值使用的应是修正后的G_t

**Comment by kklt007** [comment]
135页，“训练过程对阈值 a 并不十分敏感”，应为阈值 b。

**Comment by kklt007** [comment]
137页，描述错误，“一般而言，参数初始化的区间应该不用神经元的性质进行差异化的设置。”，应为“应该用神经元的性质进行差异化的设置”。

**Comment by kklt007** [comment]
公式6.25，n^1应改为n^l，表示第l层神经元个数。

**Comment by kklt007** [comment]
排版错误，网络优化与正则化应为全书第七章，但是pdf中的章节标题等都是写的第六章。

**Comment by xpqiu** [comment]
已修正，多谢！方便的话请告知你的名字，我会在书中致谢。
